-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
-- Version: 2019.2
-- Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity decimation1 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    ary_V_address0 : OUT STD_LOGIC_VECTOR (16 downto 0);
    ary_V_ce0 : OUT STD_LOGIC;
    ary_V_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    new_ary_V_address0 : OUT STD_LOGIC_VECTOR (13 downto 0);
    new_ary_V_ce0 : OUT STD_LOGIC;
    new_ary_V_we0 : OUT STD_LOGIC;
    new_ary_V_d0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of decimation1 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv17_0 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000000000";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv17_186A0 : STD_LOGIC_VECTOR (16 downto 0) := "11000011010100000";
    constant ap_const_lv17_1 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000000001";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_boolean_1 : BOOLEAN := true;

    signal ap_CS_fsm : STD_LOGIC_VECTOR (2 downto 0) := "001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal n_fu_73_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal n_reg_108 : STD_LOGIC_VECTOR (16 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal icmp_ln216_fu_67_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln219_fu_84_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln219_reg_118 : STD_LOGIC_VECTOR (0 downto 0);
    signal n_0_reg_51 : STD_LOGIC_VECTOR (16 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal zext_ln218_fu_79_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln222_fu_100_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln216_fu_63_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln1_fu_90_p4 : STD_LOGIC_VECTOR (13 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (2 downto 0);


begin




    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    n_0_reg_51_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                n_0_reg_51 <= n_reg_108;
            elsif (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                n_0_reg_51 <= ap_const_lv17_0;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln216_fu_67_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                icmp_ln219_reg_118 <= icmp_ln219_fu_84_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                n_reg_108 <= n_fu_73_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state2, icmp_ln216_fu_67_p2)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((icmp_ln216_fu_67_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state2;
            when others =>  
                ap_NS_fsm <= "XXX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);

    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state2, icmp_ln216_fu_67_p2)
    begin
        if ((((icmp_ln216_fu_67_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2)) or ((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state2, icmp_ln216_fu_67_p2)
    begin
        if (((icmp_ln216_fu_67_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    ary_V_address0 <= zext_ln218_fu_79_p1(17 - 1 downto 0);

    ary_V_ce0_assign_proc : process(ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            ary_V_ce0 <= ap_const_logic_1;
        else 
            ary_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    icmp_ln216_fu_67_p2 <= "1" when (n_0_reg_51 = ap_const_lv17_186A0) else "0";
    icmp_ln219_fu_84_p2 <= "1" when (trunc_ln216_fu_63_p1 = ap_const_lv3_0) else "0";
    n_fu_73_p2 <= std_logic_vector(unsigned(ap_const_lv17_1) + unsigned(n_0_reg_51));
    new_ary_V_address0 <= zext_ln222_fu_100_p1(14 - 1 downto 0);

    new_ary_V_ce0_assign_proc : process(ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            new_ary_V_ce0 <= ap_const_logic_1;
        else 
            new_ary_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    new_ary_V_d0 <= ary_V_q0;

    new_ary_V_we0_assign_proc : process(icmp_ln219_reg_118, ap_CS_fsm_state3)
    begin
        if (((icmp_ln219_reg_118 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            new_ary_V_we0 <= ap_const_logic_1;
        else 
            new_ary_V_we0 <= ap_const_logic_0;
        end if; 
    end process;

    trunc_ln1_fu_90_p4 <= n_0_reg_51(16 downto 3);
    trunc_ln216_fu_63_p1 <= n_0_reg_51(3 - 1 downto 0);
    zext_ln218_fu_79_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(n_0_reg_51),64));
    zext_ln222_fu_100_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(trunc_ln1_fu_90_p4),64));
end behav;
