// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="demodulationFM,hls_ip_2019_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=1,HLS_INPUT_PART=xc7k70t-fbv676-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=8.566000,HLS_SYN_LAT=21306586,HLS_SYN_TPT=none,HLS_SYN_MEM=1120,HLS_SYN_DSP=26,HLS_SYN_FF=2010,HLS_SYN_LUT=3373,HLS_VERSION=2019_2}" *)

module demodulationFM (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        y_I_V_address0,
        y_I_V_ce0,
        y_I_V_q0,
        y_Q_V_address0,
        y_Q_V_ce0,
        y_Q_V_q0,
        y_demod_d_V_address0,
        y_demod_d_V_ce0,
        y_demod_d_V_we0,
        y_demod_d_V_d0,
        ap_return
);

parameter    ap_ST_fsm_state1 = 115'd1;
parameter    ap_ST_fsm_state2 = 115'd2;
parameter    ap_ST_fsm_state3 = 115'd4;
parameter    ap_ST_fsm_state4 = 115'd8;
parameter    ap_ST_fsm_state5 = 115'd16;
parameter    ap_ST_fsm_state6 = 115'd32;
parameter    ap_ST_fsm_state7 = 115'd64;
parameter    ap_ST_fsm_state8 = 115'd128;
parameter    ap_ST_fsm_state9 = 115'd256;
parameter    ap_ST_fsm_state10 = 115'd512;
parameter    ap_ST_fsm_state11 = 115'd1024;
parameter    ap_ST_fsm_state12 = 115'd2048;
parameter    ap_ST_fsm_state13 = 115'd4096;
parameter    ap_ST_fsm_state14 = 115'd8192;
parameter    ap_ST_fsm_state15 = 115'd16384;
parameter    ap_ST_fsm_state16 = 115'd32768;
parameter    ap_ST_fsm_state17 = 115'd65536;
parameter    ap_ST_fsm_state18 = 115'd131072;
parameter    ap_ST_fsm_state19 = 115'd262144;
parameter    ap_ST_fsm_state20 = 115'd524288;
parameter    ap_ST_fsm_state21 = 115'd1048576;
parameter    ap_ST_fsm_state22 = 115'd2097152;
parameter    ap_ST_fsm_state23 = 115'd4194304;
parameter    ap_ST_fsm_state24 = 115'd8388608;
parameter    ap_ST_fsm_state25 = 115'd16777216;
parameter    ap_ST_fsm_state26 = 115'd33554432;
parameter    ap_ST_fsm_state27 = 115'd67108864;
parameter    ap_ST_fsm_state28 = 115'd134217728;
parameter    ap_ST_fsm_state29 = 115'd268435456;
parameter    ap_ST_fsm_state30 = 115'd536870912;
parameter    ap_ST_fsm_state31 = 115'd1073741824;
parameter    ap_ST_fsm_state32 = 115'd2147483648;
parameter    ap_ST_fsm_state33 = 115'd4294967296;
parameter    ap_ST_fsm_state34 = 115'd8589934592;
parameter    ap_ST_fsm_state35 = 115'd17179869184;
parameter    ap_ST_fsm_state36 = 115'd34359738368;
parameter    ap_ST_fsm_state37 = 115'd68719476736;
parameter    ap_ST_fsm_state38 = 115'd137438953472;
parameter    ap_ST_fsm_state39 = 115'd274877906944;
parameter    ap_ST_fsm_state40 = 115'd549755813888;
parameter    ap_ST_fsm_state41 = 115'd1099511627776;
parameter    ap_ST_fsm_state42 = 115'd2199023255552;
parameter    ap_ST_fsm_state43 = 115'd4398046511104;
parameter    ap_ST_fsm_state44 = 115'd8796093022208;
parameter    ap_ST_fsm_state45 = 115'd17592186044416;
parameter    ap_ST_fsm_state46 = 115'd35184372088832;
parameter    ap_ST_fsm_state47 = 115'd70368744177664;
parameter    ap_ST_fsm_state48 = 115'd140737488355328;
parameter    ap_ST_fsm_state49 = 115'd281474976710656;
parameter    ap_ST_fsm_state50 = 115'd562949953421312;
parameter    ap_ST_fsm_state51 = 115'd1125899906842624;
parameter    ap_ST_fsm_state52 = 115'd2251799813685248;
parameter    ap_ST_fsm_state53 = 115'd4503599627370496;
parameter    ap_ST_fsm_state54 = 115'd9007199254740992;
parameter    ap_ST_fsm_state55 = 115'd18014398509481984;
parameter    ap_ST_fsm_state56 = 115'd36028797018963968;
parameter    ap_ST_fsm_state57 = 115'd72057594037927936;
parameter    ap_ST_fsm_state58 = 115'd144115188075855872;
parameter    ap_ST_fsm_state59 = 115'd288230376151711744;
parameter    ap_ST_fsm_state60 = 115'd576460752303423488;
parameter    ap_ST_fsm_state61 = 115'd1152921504606846976;
parameter    ap_ST_fsm_state62 = 115'd2305843009213693952;
parameter    ap_ST_fsm_state63 = 115'd4611686018427387904;
parameter    ap_ST_fsm_state64 = 115'd9223372036854775808;
parameter    ap_ST_fsm_state65 = 115'd18446744073709551616;
parameter    ap_ST_fsm_state66 = 115'd36893488147419103232;
parameter    ap_ST_fsm_state67 = 115'd73786976294838206464;
parameter    ap_ST_fsm_state68 = 115'd147573952589676412928;
parameter    ap_ST_fsm_state69 = 115'd295147905179352825856;
parameter    ap_ST_fsm_state70 = 115'd590295810358705651712;
parameter    ap_ST_fsm_state71 = 115'd1180591620717411303424;
parameter    ap_ST_fsm_state72 = 115'd2361183241434822606848;
parameter    ap_ST_fsm_state73 = 115'd4722366482869645213696;
parameter    ap_ST_fsm_state74 = 115'd9444732965739290427392;
parameter    ap_ST_fsm_state75 = 115'd18889465931478580854784;
parameter    ap_ST_fsm_state76 = 115'd37778931862957161709568;
parameter    ap_ST_fsm_state77 = 115'd75557863725914323419136;
parameter    ap_ST_fsm_state78 = 115'd151115727451828646838272;
parameter    ap_ST_fsm_state79 = 115'd302231454903657293676544;
parameter    ap_ST_fsm_state80 = 115'd604462909807314587353088;
parameter    ap_ST_fsm_state81 = 115'd1208925819614629174706176;
parameter    ap_ST_fsm_state82 = 115'd2417851639229258349412352;
parameter    ap_ST_fsm_state83 = 115'd4835703278458516698824704;
parameter    ap_ST_fsm_state84 = 115'd9671406556917033397649408;
parameter    ap_ST_fsm_state85 = 115'd19342813113834066795298816;
parameter    ap_ST_fsm_state86 = 115'd38685626227668133590597632;
parameter    ap_ST_fsm_state87 = 115'd77371252455336267181195264;
parameter    ap_ST_fsm_state88 = 115'd154742504910672534362390528;
parameter    ap_ST_fsm_state89 = 115'd309485009821345068724781056;
parameter    ap_ST_fsm_state90 = 115'd618970019642690137449562112;
parameter    ap_ST_fsm_state91 = 115'd1237940039285380274899124224;
parameter    ap_ST_fsm_state92 = 115'd2475880078570760549798248448;
parameter    ap_ST_fsm_state93 = 115'd4951760157141521099596496896;
parameter    ap_ST_fsm_state94 = 115'd9903520314283042199192993792;
parameter    ap_ST_fsm_state95 = 115'd19807040628566084398385987584;
parameter    ap_ST_fsm_state96 = 115'd39614081257132168796771975168;
parameter    ap_ST_fsm_state97 = 115'd79228162514264337593543950336;
parameter    ap_ST_fsm_state98 = 115'd158456325028528675187087900672;
parameter    ap_ST_fsm_state99 = 115'd316912650057057350374175801344;
parameter    ap_ST_fsm_state100 = 115'd633825300114114700748351602688;
parameter    ap_ST_fsm_state101 = 115'd1267650600228229401496703205376;
parameter    ap_ST_fsm_state102 = 115'd2535301200456458802993406410752;
parameter    ap_ST_fsm_state103 = 115'd5070602400912917605986812821504;
parameter    ap_ST_fsm_state104 = 115'd10141204801825835211973625643008;
parameter    ap_ST_fsm_state105 = 115'd20282409603651670423947251286016;
parameter    ap_ST_fsm_state106 = 115'd40564819207303340847894502572032;
parameter    ap_ST_fsm_state107 = 115'd81129638414606681695789005144064;
parameter    ap_ST_fsm_state108 = 115'd162259276829213363391578010288128;
parameter    ap_ST_fsm_state109 = 115'd324518553658426726783156020576256;
parameter    ap_ST_fsm_state110 = 115'd649037107316853453566312041152512;
parameter    ap_ST_fsm_state111 = 115'd1298074214633706907132624082305024;
parameter    ap_ST_fsm_state112 = 115'd2596148429267413814265248164610048;
parameter    ap_ST_fsm_state113 = 115'd5192296858534827628530496329220096;
parameter    ap_ST_fsm_state114 = 115'd10384593717069655257060992658440192;
parameter    ap_ST_fsm_state115 = 115'd20769187434139310514121985316880384;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [16:0] y_I_V_address0;
output   y_I_V_ce0;
input  [31:0] y_I_V_q0;
output  [16:0] y_Q_V_address0;
output   y_Q_V_ce0;
input  [31:0] y_Q_V_q0;
output  [10:0] y_demod_d_V_address0;
output   y_demod_d_V_ce0;
output   y_demod_d_V_we0;
output  [31:0] y_demod_d_V_d0;
output  [31:0] ap_return;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg y_demod_d_V_ce0;
reg y_demod_d_V_we0;

(* fsm_encoding = "none" *) reg   [114:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire    ap_CS_fsm_state9;
wire   [31:0] y_I_d_V_q0;
wire    ap_CS_fsm_state10;
wire   [31:0] y_Q_d_V_q0;
wire   [63:0] zext_ln255_fu_276_p1;
reg   [63:0] zext_ln255_reg_474;
wire    ap_CS_fsm_state11;
wire   [0:0] icmp_ln252_fu_270_p2;
wire   [13:0] q_fu_282_p2;
reg   [13:0] q_reg_489;
reg  signed [31:0] ary_r_value_1_V_reg_494;
wire    ap_CS_fsm_state12;
reg  signed [31:0] ary_i_value_1_V_reg_500;
wire   [31:0] dii_V_fu_288_p2;
reg   [31:0] dii_V_reg_506;
wire   [31:0] dqq_V_fu_294_p2;
reg   [31:0] dqq_V_reg_511;
wire   [63:0] ret_V_fu_324_p2;
reg   [63:0] ret_V_reg_516;
wire    ap_CS_fsm_state13;
wire   [64:0] ret_V_6_fu_350_p2;
reg  signed [64:0] ret_V_6_reg_521;
wire    ap_CS_fsm_state14;
wire   [13:0] n_fu_389_p2;
reg   [13:0] n_reg_539;
wire    ap_CS_fsm_state114;
wire   [0:0] icmp_ln230_fu_383_p2;
wire   [28:0] add_ln233_fu_410_p2;
wire    ap_CS_fsm_state115;
wire   [13:0] select_ln230_fu_443_p3;
reg   [16:0] y_I_s_V_address0;
reg    y_I_s_V_ce0;
reg    y_I_s_V_we0;
wire   [31:0] y_I_s_V_q0;
reg   [16:0] y_Q_s_V_address0;
reg    y_Q_s_V_ce0;
reg    y_Q_s_V_we0;
wire   [31:0] y_Q_s_V_q0;
reg   [16:0] y_I_fpb_V_address0;
reg    y_I_fpb_V_ce0;
reg    y_I_fpb_V_we0;
wire   [31:0] y_I_fpb_V_q0;
reg   [16:0] y_Q_fpb_V_address0;
reg    y_Q_fpb_V_ce0;
reg    y_Q_fpb_V_we0;
wire   [31:0] y_Q_fpb_V_q0;
reg   [13:0] y_I_d_V_address0;
reg    y_I_d_V_ce0;
reg    y_I_d_V_we0;
reg   [13:0] y_Q_d_V_address0;
reg    y_Q_d_V_ce0;
reg    y_Q_d_V_we0;
reg   [13:0] y_demod_nd_V_address0;
reg    y_demod_nd_V_ce0;
reg    y_demod_nd_V_we0;
reg   [31:0] y_demod_nd_V_d0;
wire   [31:0] y_demod_nd_V_q0;
wire    grp_shift_fu_240_ap_start;
wire    grp_shift_fu_240_ap_done;
wire    grp_shift_fu_240_ap_idle;
wire    grp_shift_fu_240_ap_ready;
wire   [16:0] grp_shift_fu_240_ary_r_V_address0;
wire    grp_shift_fu_240_ary_r_V_ce0;
wire   [16:0] grp_shift_fu_240_ary_i_V_address0;
wire    grp_shift_fu_240_ary_i_V_ce0;
wire   [16:0] grp_shift_fu_240_ary_r_s_V_address0;
wire    grp_shift_fu_240_ary_r_s_V_ce0;
wire    grp_shift_fu_240_ary_r_s_V_we0;
wire   [31:0] grp_shift_fu_240_ary_r_s_V_d0;
wire   [16:0] grp_shift_fu_240_ary_i_s_V_address0;
wire    grp_shift_fu_240_ary_i_s_V_ce0;
wire    grp_shift_fu_240_ary_i_s_V_we0;
wire   [31:0] grp_shift_fu_240_ary_i_s_V_d0;
wire    grp_fir_fu_256_ap_start;
wire    grp_fir_fu_256_ap_done;
wire    grp_fir_fu_256_ap_idle;
wire    grp_fir_fu_256_ap_ready;
wire   [16:0] grp_fir_fu_256_x_V_address0;
wire    grp_fir_fu_256_x_V_ce0;
reg   [31:0] grp_fir_fu_256_x_V_q0;
wire   [16:0] grp_fir_fu_256_y_V_address0;
wire    grp_fir_fu_256_y_V_ce0;
wire    grp_fir_fu_256_y_V_we0;
wire   [31:0] grp_fir_fu_256_y_V_d0;
wire    grp_decimation1_fu_264_ap_start;
wire    grp_decimation1_fu_264_ap_done;
wire    grp_decimation1_fu_264_ap_idle;
wire    grp_decimation1_fu_264_ap_ready;
wire   [16:0] grp_decimation1_fu_264_ary_V_address0;
wire    grp_decimation1_fu_264_ary_V_ce0;
reg   [31:0] grp_decimation1_fu_264_ary_V_q0;
wire   [13:0] grp_decimation1_fu_264_new_ary_V_address0;
wire    grp_decimation1_fu_264_new_ary_V_ce0;
wire    grp_decimation1_fu_264_new_ary_V_we0;
wire   [31:0] grp_decimation1_fu_264_new_ary_V_d0;
reg   [31:0] p_Val2_13_reg_174;
wire    ap_CS_fsm_state113;
reg   [31:0] p_Val2_15_reg_184;
reg   [13:0] q_0_i_reg_194;
reg   [13:0] n_0_i_reg_205;
reg   [28:0] phi_mul_reg_216;
reg   [13:0] phi_urem_reg_228;
reg    grp_shift_fu_240_ap_start_reg;
wire    ap_CS_fsm_state2;
reg    grp_fir_fu_256_ap_start_reg;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state5;
wire    ap_CS_fsm_state4;
wire    ap_CS_fsm_state6;
reg    grp_decimation1_fu_264_ap_start_reg;
wire    ap_CS_fsm_state7;
wire    ap_CS_fsm_state8;
wire   [63:0] zext_ln232_fu_395_p1;
wire   [63:0] zext_ln236_fu_426_p1;
wire   [0:0] icmp_ln233_fu_404_p2;
wire  signed [31:0] dii_V_fu_288_p0;
wire  signed [31:0] dqq_V_fu_294_p0;
wire  signed [31:0] r_V_6_fu_306_p0;
wire  signed [31:0] r_V_6_fu_306_p1;
wire  signed [63:0] r_V_fu_300_p1;
wire  signed [31:0] r_V_7_fu_318_p0;
wire  signed [63:0] r_V_2_fu_312_p1;
wire  signed [31:0] r_V_7_fu_318_p1;
wire   [63:0] r_V_6_fu_306_p2;
wire   [63:0] r_V_7_fu_318_p2;
wire  signed [31:0] r_V_8_fu_330_p0;
wire  signed [31:0] r_V_8_fu_330_p1;
wire  signed [31:0] r_V_9_fu_336_p0;
wire  signed [31:0] r_V_9_fu_336_p1;
wire   [63:0] r_V_8_fu_330_p2;
wire   [63:0] r_V_9_fu_336_p2;
wire  signed [64:0] rhs_V_fu_346_p1;
wire  signed [64:0] lhs_V_fu_342_p1;
wire   [95:0] grp_fu_366_p0;
wire   [95:0] grp_fu_366_p2;
wire   [3:0] trunc_ln233_fu_400_p1;
wire   [10:0] tmp_14_fu_416_p4;
wire   [13:0] add_ln230_1_fu_431_p2;
wire   [0:0] icmp_ln230_1_fu_437_p2;
reg    grp_fu_366_ap_start;
wire    grp_fu_366_ap_done;
reg   [114:0] ap_NS_fsm;
reg    ap_block_state6_on_subcall_done;

// power-on initialization
initial begin
#0 ap_CS_fsm = 115'd1;
#0 grp_shift_fu_240_ap_start_reg = 1'b0;
#0 grp_fir_fu_256_ap_start_reg = 1'b0;
#0 grp_decimation1_fu_264_ap_start_reg = 1'b0;
end

demodulationFM_y_bkb #(
    .DataWidth( 32 ),
    .AddressRange( 100000 ),
    .AddressWidth( 17 ))
y_I_s_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(y_I_s_V_address0),
    .ce0(y_I_s_V_ce0),
    .we0(y_I_s_V_we0),
    .d0(grp_shift_fu_240_ary_r_s_V_d0),
    .q0(y_I_s_V_q0)
);

demodulationFM_y_bkb #(
    .DataWidth( 32 ),
    .AddressRange( 100000 ),
    .AddressWidth( 17 ))
y_Q_s_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(y_Q_s_V_address0),
    .ce0(y_Q_s_V_ce0),
    .we0(y_Q_s_V_we0),
    .d0(grp_shift_fu_240_ary_i_s_V_d0),
    .q0(y_Q_s_V_q0)
);

demodulationFM_y_bkb #(
    .DataWidth( 32 ),
    .AddressRange( 100000 ),
    .AddressWidth( 17 ))
y_I_fpb_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(y_I_fpb_V_address0),
    .ce0(y_I_fpb_V_ce0),
    .we0(y_I_fpb_V_we0),
    .d0(grp_fir_fu_256_y_V_d0),
    .q0(y_I_fpb_V_q0)
);

demodulationFM_y_bkb #(
    .DataWidth( 32 ),
    .AddressRange( 100000 ),
    .AddressWidth( 17 ))
y_Q_fpb_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(y_Q_fpb_V_address0),
    .ce0(y_Q_fpb_V_ce0),
    .we0(y_Q_fpb_V_we0),
    .d0(grp_fir_fu_256_y_V_d0),
    .q0(y_Q_fpb_V_q0)
);

demodulationFM_y_fYi #(
    .DataWidth( 32 ),
    .AddressRange( 12500 ),
    .AddressWidth( 14 ))
y_I_d_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(y_I_d_V_address0),
    .ce0(y_I_d_V_ce0),
    .we0(y_I_d_V_we0),
    .d0(grp_decimation1_fu_264_new_ary_V_d0),
    .q0(y_I_d_V_q0)
);

demodulationFM_y_fYi #(
    .DataWidth( 32 ),
    .AddressRange( 12500 ),
    .AddressWidth( 14 ))
y_Q_d_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(y_Q_d_V_address0),
    .ce0(y_Q_d_V_ce0),
    .we0(y_Q_d_V_we0),
    .d0(grp_decimation1_fu_264_new_ary_V_d0),
    .q0(y_Q_d_V_q0)
);

demodulationFM_y_fYi #(
    .DataWidth( 32 ),
    .AddressRange( 12500 ),
    .AddressWidth( 14 ))
y_demod_nd_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(y_demod_nd_V_address0),
    .ce0(y_demod_nd_V_ce0),
    .we0(y_demod_nd_V_we0),
    .d0(y_demod_nd_V_d0),
    .q0(y_demod_nd_V_q0)
);

shift grp_shift_fu_240(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_shift_fu_240_ap_start),
    .ap_done(grp_shift_fu_240_ap_done),
    .ap_idle(grp_shift_fu_240_ap_idle),
    .ap_ready(grp_shift_fu_240_ap_ready),
    .ary_r_V_address0(grp_shift_fu_240_ary_r_V_address0),
    .ary_r_V_ce0(grp_shift_fu_240_ary_r_V_ce0),
    .ary_r_V_q0(y_I_V_q0),
    .ary_i_V_address0(grp_shift_fu_240_ary_i_V_address0),
    .ary_i_V_ce0(grp_shift_fu_240_ary_i_V_ce0),
    .ary_i_V_q0(y_Q_V_q0),
    .ary_r_s_V_address0(grp_shift_fu_240_ary_r_s_V_address0),
    .ary_r_s_V_ce0(grp_shift_fu_240_ary_r_s_V_ce0),
    .ary_r_s_V_we0(grp_shift_fu_240_ary_r_s_V_we0),
    .ary_r_s_V_d0(grp_shift_fu_240_ary_r_s_V_d0),
    .ary_i_s_V_address0(grp_shift_fu_240_ary_i_s_V_address0),
    .ary_i_s_V_ce0(grp_shift_fu_240_ary_i_s_V_ce0),
    .ary_i_s_V_we0(grp_shift_fu_240_ary_i_s_V_we0),
    .ary_i_s_V_d0(grp_shift_fu_240_ary_i_s_V_d0)
);

fir grp_fir_fu_256(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_fir_fu_256_ap_start),
    .ap_done(grp_fir_fu_256_ap_done),
    .ap_idle(grp_fir_fu_256_ap_idle),
    .ap_ready(grp_fir_fu_256_ap_ready),
    .x_V_address0(grp_fir_fu_256_x_V_address0),
    .x_V_ce0(grp_fir_fu_256_x_V_ce0),
    .x_V_q0(grp_fir_fu_256_x_V_q0),
    .y_V_address0(grp_fir_fu_256_y_V_address0),
    .y_V_ce0(grp_fir_fu_256_y_V_ce0),
    .y_V_we0(grp_fir_fu_256_y_V_we0),
    .y_V_d0(grp_fir_fu_256_y_V_d0)
);

decimation1 grp_decimation1_fu_264(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_decimation1_fu_264_ap_start),
    .ap_done(grp_decimation1_fu_264_ap_done),
    .ap_idle(grp_decimation1_fu_264_ap_idle),
    .ap_ready(grp_decimation1_fu_264_ap_ready),
    .ary_V_address0(grp_decimation1_fu_264_ary_V_address0),
    .ary_V_ce0(grp_decimation1_fu_264_ary_V_ce0),
    .ary_V_q0(grp_decimation1_fu_264_ary_V_q0),
    .new_ary_V_address0(grp_decimation1_fu_264_new_ary_V_address0),
    .new_ary_V_ce0(grp_decimation1_fu_264_new_ary_V_ce0),
    .new_ary_V_we0(grp_decimation1_fu_264_new_ary_V_we0),
    .new_ary_V_d0(grp_decimation1_fu_264_new_ary_V_d0)
);

demodulationFM_sdibs #(
    .ID( 1 ),
    .NUM_STAGE( 100 ),
    .din0_WIDTH( 96 ),
    .din1_WIDTH( 65 ),
    .dout_WIDTH( 96 ))
demodulationFM_sdibs_U13(
    .clk(ap_clk),
    .reset(ap_rst),
    .start(grp_fu_366_ap_start),
    .done(grp_fu_366_ap_done),
    .din0(grp_fu_366_p0),
    .din1(ret_V_6_reg_521),
    .ce(1'b1),
    .dout(grp_fu_366_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_decimation1_fu_264_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state5))) begin
            grp_decimation1_fu_264_ap_start_reg <= 1'b1;
        end else if ((grp_decimation1_fu_264_ap_ready == 1'b1)) begin
            grp_decimation1_fu_264_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_fir_fu_256_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state3))) begin
            grp_fir_fu_256_ap_start_reg <= 1'b1;
        end else if ((grp_fir_fu_256_ap_ready == 1'b1)) begin
            grp_fir_fu_256_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_shift_fu_240_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            grp_shift_fu_240_ap_start_reg <= 1'b1;
        end else if ((grp_shift_fu_240_ap_ready == 1'b1)) begin
            grp_shift_fu_240_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state11) & (icmp_ln252_fu_270_p2 == 1'd1))) begin
        n_0_i_reg_205 <= 14'd0;
    end else if ((1'b1 == ap_CS_fsm_state115)) begin
        n_0_i_reg_205 <= n_reg_539;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state113)) begin
        p_Val2_13_reg_174 <= ary_r_value_1_V_reg_494;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        p_Val2_13_reg_174 <= y_I_d_V_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state113)) begin
        p_Val2_15_reg_184 <= ary_i_value_1_V_reg_500;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        p_Val2_15_reg_184 <= y_Q_d_V_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state11) & (icmp_ln252_fu_270_p2 == 1'd1))) begin
        phi_mul_reg_216 <= 29'd0;
    end else if ((1'b1 == ap_CS_fsm_state115)) begin
        phi_mul_reg_216 <= add_ln233_fu_410_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state11) & (icmp_ln252_fu_270_p2 == 1'd1))) begin
        phi_urem_reg_228 <= 14'd0;
    end else if ((1'b1 == ap_CS_fsm_state115)) begin
        phi_urem_reg_228 <= select_ln230_fu_443_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state113)) begin
        q_0_i_reg_194 <= q_reg_489;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        q_0_i_reg_194 <= 14'd1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        ary_i_value_1_V_reg_500 <= y_Q_d_V_q0;
        ary_r_value_1_V_reg_494 <= y_I_d_V_q0;
        dii_V_reg_506 <= dii_V_fu_288_p2;
        dqq_V_reg_511 <= dqq_V_fu_294_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state114)) begin
        n_reg_539 <= n_fu_389_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state11) & (icmp_ln252_fu_270_p2 == 1'd0))) begin
        q_reg_489 <= q_fu_282_p2;
        zext_ln255_reg_474[13 : 0] <= zext_ln255_fu_276_p1[13 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        ret_V_6_reg_521 <= ret_V_6_fu_350_p2;
        ret_V_reg_516 <= ret_V_fu_324_p2;
    end
end

always @ (*) begin
    if (((icmp_ln230_fu_383_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state114))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln230_fu_383_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state114))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        grp_decimation1_fu_264_ary_V_q0 = y_Q_fpb_V_q0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        grp_decimation1_fu_264_ary_V_q0 = y_I_fpb_V_q0;
    end else begin
        grp_decimation1_fu_264_ary_V_q0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        grp_fir_fu_256_x_V_q0 = y_Q_s_V_q0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fir_fu_256_x_V_q0 = y_I_s_V_q0;
    end else begin
        grp_fir_fu_256_x_V_q0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        grp_fu_366_ap_start = 1'b1;
    end else begin
        grp_fu_366_ap_start = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        y_I_d_V_address0 = zext_ln255_fu_276_p1;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        y_I_d_V_address0 = 64'd0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        y_I_d_V_address0 = grp_decimation1_fu_264_new_ary_V_address0;
    end else begin
        y_I_d_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state9))) begin
        y_I_d_V_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        y_I_d_V_ce0 = grp_decimation1_fu_264_new_ary_V_ce0;
    end else begin
        y_I_d_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        y_I_d_V_we0 = grp_decimation1_fu_264_new_ary_V_we0;
    end else begin
        y_I_d_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        y_I_fpb_V_address0 = grp_decimation1_fu_264_ary_V_address0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        y_I_fpb_V_address0 = grp_fir_fu_256_y_V_address0;
    end else begin
        y_I_fpb_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        y_I_fpb_V_ce0 = grp_decimation1_fu_264_ary_V_ce0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        y_I_fpb_V_ce0 = grp_fir_fu_256_y_V_ce0;
    end else begin
        y_I_fpb_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        y_I_fpb_V_we0 = grp_fir_fu_256_y_V_we0;
    end else begin
        y_I_fpb_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        y_I_s_V_address0 = grp_fir_fu_256_x_V_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        y_I_s_V_address0 = grp_shift_fu_240_ary_r_s_V_address0;
    end else begin
        y_I_s_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        y_I_s_V_ce0 = grp_fir_fu_256_x_V_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        y_I_s_V_ce0 = grp_shift_fu_240_ary_r_s_V_ce0;
    end else begin
        y_I_s_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        y_I_s_V_we0 = grp_shift_fu_240_ary_r_s_V_we0;
    end else begin
        y_I_s_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        y_Q_d_V_address0 = zext_ln255_fu_276_p1;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        y_Q_d_V_address0 = 64'd0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        y_Q_d_V_address0 = grp_decimation1_fu_264_new_ary_V_address0;
    end else begin
        y_Q_d_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state9))) begin
        y_Q_d_V_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        y_Q_d_V_ce0 = grp_decimation1_fu_264_new_ary_V_ce0;
    end else begin
        y_Q_d_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        y_Q_d_V_we0 = grp_decimation1_fu_264_new_ary_V_we0;
    end else begin
        y_Q_d_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        y_Q_fpb_V_address0 = grp_decimation1_fu_264_ary_V_address0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        y_Q_fpb_V_address0 = grp_fir_fu_256_y_V_address0;
    end else begin
        y_Q_fpb_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        y_Q_fpb_V_ce0 = grp_decimation1_fu_264_ary_V_ce0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        y_Q_fpb_V_ce0 = grp_fir_fu_256_y_V_ce0;
    end else begin
        y_Q_fpb_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        y_Q_fpb_V_we0 = grp_fir_fu_256_y_V_we0;
    end else begin
        y_Q_fpb_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        y_Q_s_V_address0 = grp_fir_fu_256_x_V_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        y_Q_s_V_address0 = grp_shift_fu_240_ary_i_s_V_address0;
    end else begin
        y_Q_s_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        y_Q_s_V_ce0 = grp_fir_fu_256_x_V_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        y_Q_s_V_ce0 = grp_shift_fu_240_ary_i_s_V_ce0;
    end else begin
        y_Q_s_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        y_Q_s_V_we0 = grp_shift_fu_240_ary_i_s_V_we0;
    end else begin
        y_Q_s_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state115)) begin
        y_demod_d_V_ce0 = 1'b1;
    end else begin
        y_demod_d_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln233_fu_404_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state115))) begin
        y_demod_d_V_we0 = 1'b1;
    end else begin
        y_demod_d_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state114)) begin
        y_demod_nd_V_address0 = zext_ln232_fu_395_p1;
    end else if ((1'b1 == ap_CS_fsm_state113)) begin
        y_demod_nd_V_address0 = zext_ln255_reg_474;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        y_demod_nd_V_address0 = 64'd0;
    end else begin
        y_demod_nd_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state113) | (1'b1 == ap_CS_fsm_state114) | (1'b1 == ap_CS_fsm_state10))) begin
        y_demod_nd_V_ce0 = 1'b1;
    end else begin
        y_demod_nd_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state113)) begin
        y_demod_nd_V_d0 = {{grp_fu_366_p2[47:16]}};
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        y_demod_nd_V_d0 = 32'd0;
    end else begin
        y_demod_nd_V_d0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state113) | (1'b1 == ap_CS_fsm_state10))) begin
        y_demod_nd_V_we0 = 1'b1;
    end else begin
        y_demod_nd_V_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((grp_shift_fu_240_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((grp_fir_fu_256_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            if (((1'b0 == ap_block_state6_on_subcall_done) & (1'b1 == ap_CS_fsm_state6))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            if (((grp_decimation1_fu_264_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state8))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            if (((1'b1 == ap_CS_fsm_state11) & (icmp_ln252_fu_270_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state114;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state21 : begin
            ap_NS_fsm = ap_ST_fsm_state22;
        end
        ap_ST_fsm_state22 : begin
            ap_NS_fsm = ap_ST_fsm_state23;
        end
        ap_ST_fsm_state23 : begin
            ap_NS_fsm = ap_ST_fsm_state24;
        end
        ap_ST_fsm_state24 : begin
            ap_NS_fsm = ap_ST_fsm_state25;
        end
        ap_ST_fsm_state25 : begin
            ap_NS_fsm = ap_ST_fsm_state26;
        end
        ap_ST_fsm_state26 : begin
            ap_NS_fsm = ap_ST_fsm_state27;
        end
        ap_ST_fsm_state27 : begin
            ap_NS_fsm = ap_ST_fsm_state28;
        end
        ap_ST_fsm_state28 : begin
            ap_NS_fsm = ap_ST_fsm_state29;
        end
        ap_ST_fsm_state29 : begin
            ap_NS_fsm = ap_ST_fsm_state30;
        end
        ap_ST_fsm_state30 : begin
            ap_NS_fsm = ap_ST_fsm_state31;
        end
        ap_ST_fsm_state31 : begin
            ap_NS_fsm = ap_ST_fsm_state32;
        end
        ap_ST_fsm_state32 : begin
            ap_NS_fsm = ap_ST_fsm_state33;
        end
        ap_ST_fsm_state33 : begin
            ap_NS_fsm = ap_ST_fsm_state34;
        end
        ap_ST_fsm_state34 : begin
            ap_NS_fsm = ap_ST_fsm_state35;
        end
        ap_ST_fsm_state35 : begin
            ap_NS_fsm = ap_ST_fsm_state36;
        end
        ap_ST_fsm_state36 : begin
            ap_NS_fsm = ap_ST_fsm_state37;
        end
        ap_ST_fsm_state37 : begin
            ap_NS_fsm = ap_ST_fsm_state38;
        end
        ap_ST_fsm_state38 : begin
            ap_NS_fsm = ap_ST_fsm_state39;
        end
        ap_ST_fsm_state39 : begin
            ap_NS_fsm = ap_ST_fsm_state40;
        end
        ap_ST_fsm_state40 : begin
            ap_NS_fsm = ap_ST_fsm_state41;
        end
        ap_ST_fsm_state41 : begin
            ap_NS_fsm = ap_ST_fsm_state42;
        end
        ap_ST_fsm_state42 : begin
            ap_NS_fsm = ap_ST_fsm_state43;
        end
        ap_ST_fsm_state43 : begin
            ap_NS_fsm = ap_ST_fsm_state44;
        end
        ap_ST_fsm_state44 : begin
            ap_NS_fsm = ap_ST_fsm_state45;
        end
        ap_ST_fsm_state45 : begin
            ap_NS_fsm = ap_ST_fsm_state46;
        end
        ap_ST_fsm_state46 : begin
            ap_NS_fsm = ap_ST_fsm_state47;
        end
        ap_ST_fsm_state47 : begin
            ap_NS_fsm = ap_ST_fsm_state48;
        end
        ap_ST_fsm_state48 : begin
            ap_NS_fsm = ap_ST_fsm_state49;
        end
        ap_ST_fsm_state49 : begin
            ap_NS_fsm = ap_ST_fsm_state50;
        end
        ap_ST_fsm_state50 : begin
            ap_NS_fsm = ap_ST_fsm_state51;
        end
        ap_ST_fsm_state51 : begin
            ap_NS_fsm = ap_ST_fsm_state52;
        end
        ap_ST_fsm_state52 : begin
            ap_NS_fsm = ap_ST_fsm_state53;
        end
        ap_ST_fsm_state53 : begin
            ap_NS_fsm = ap_ST_fsm_state54;
        end
        ap_ST_fsm_state54 : begin
            ap_NS_fsm = ap_ST_fsm_state55;
        end
        ap_ST_fsm_state55 : begin
            ap_NS_fsm = ap_ST_fsm_state56;
        end
        ap_ST_fsm_state56 : begin
            ap_NS_fsm = ap_ST_fsm_state57;
        end
        ap_ST_fsm_state57 : begin
            ap_NS_fsm = ap_ST_fsm_state58;
        end
        ap_ST_fsm_state58 : begin
            ap_NS_fsm = ap_ST_fsm_state59;
        end
        ap_ST_fsm_state59 : begin
            ap_NS_fsm = ap_ST_fsm_state60;
        end
        ap_ST_fsm_state60 : begin
            ap_NS_fsm = ap_ST_fsm_state61;
        end
        ap_ST_fsm_state61 : begin
            ap_NS_fsm = ap_ST_fsm_state62;
        end
        ap_ST_fsm_state62 : begin
            ap_NS_fsm = ap_ST_fsm_state63;
        end
        ap_ST_fsm_state63 : begin
            ap_NS_fsm = ap_ST_fsm_state64;
        end
        ap_ST_fsm_state64 : begin
            ap_NS_fsm = ap_ST_fsm_state65;
        end
        ap_ST_fsm_state65 : begin
            ap_NS_fsm = ap_ST_fsm_state66;
        end
        ap_ST_fsm_state66 : begin
            ap_NS_fsm = ap_ST_fsm_state67;
        end
        ap_ST_fsm_state67 : begin
            ap_NS_fsm = ap_ST_fsm_state68;
        end
        ap_ST_fsm_state68 : begin
            ap_NS_fsm = ap_ST_fsm_state69;
        end
        ap_ST_fsm_state69 : begin
            ap_NS_fsm = ap_ST_fsm_state70;
        end
        ap_ST_fsm_state70 : begin
            ap_NS_fsm = ap_ST_fsm_state71;
        end
        ap_ST_fsm_state71 : begin
            ap_NS_fsm = ap_ST_fsm_state72;
        end
        ap_ST_fsm_state72 : begin
            ap_NS_fsm = ap_ST_fsm_state73;
        end
        ap_ST_fsm_state73 : begin
            ap_NS_fsm = ap_ST_fsm_state74;
        end
        ap_ST_fsm_state74 : begin
            ap_NS_fsm = ap_ST_fsm_state75;
        end
        ap_ST_fsm_state75 : begin
            ap_NS_fsm = ap_ST_fsm_state76;
        end
        ap_ST_fsm_state76 : begin
            ap_NS_fsm = ap_ST_fsm_state77;
        end
        ap_ST_fsm_state77 : begin
            ap_NS_fsm = ap_ST_fsm_state78;
        end
        ap_ST_fsm_state78 : begin
            ap_NS_fsm = ap_ST_fsm_state79;
        end
        ap_ST_fsm_state79 : begin
            ap_NS_fsm = ap_ST_fsm_state80;
        end
        ap_ST_fsm_state80 : begin
            ap_NS_fsm = ap_ST_fsm_state81;
        end
        ap_ST_fsm_state81 : begin
            ap_NS_fsm = ap_ST_fsm_state82;
        end
        ap_ST_fsm_state82 : begin
            ap_NS_fsm = ap_ST_fsm_state83;
        end
        ap_ST_fsm_state83 : begin
            ap_NS_fsm = ap_ST_fsm_state84;
        end
        ap_ST_fsm_state84 : begin
            ap_NS_fsm = ap_ST_fsm_state85;
        end
        ap_ST_fsm_state85 : begin
            ap_NS_fsm = ap_ST_fsm_state86;
        end
        ap_ST_fsm_state86 : begin
            ap_NS_fsm = ap_ST_fsm_state87;
        end
        ap_ST_fsm_state87 : begin
            ap_NS_fsm = ap_ST_fsm_state88;
        end
        ap_ST_fsm_state88 : begin
            ap_NS_fsm = ap_ST_fsm_state89;
        end
        ap_ST_fsm_state89 : begin
            ap_NS_fsm = ap_ST_fsm_state90;
        end
        ap_ST_fsm_state90 : begin
            ap_NS_fsm = ap_ST_fsm_state91;
        end
        ap_ST_fsm_state91 : begin
            ap_NS_fsm = ap_ST_fsm_state92;
        end
        ap_ST_fsm_state92 : begin
            ap_NS_fsm = ap_ST_fsm_state93;
        end
        ap_ST_fsm_state93 : begin
            ap_NS_fsm = ap_ST_fsm_state94;
        end
        ap_ST_fsm_state94 : begin
            ap_NS_fsm = ap_ST_fsm_state95;
        end
        ap_ST_fsm_state95 : begin
            ap_NS_fsm = ap_ST_fsm_state96;
        end
        ap_ST_fsm_state96 : begin
            ap_NS_fsm = ap_ST_fsm_state97;
        end
        ap_ST_fsm_state97 : begin
            ap_NS_fsm = ap_ST_fsm_state98;
        end
        ap_ST_fsm_state98 : begin
            ap_NS_fsm = ap_ST_fsm_state99;
        end
        ap_ST_fsm_state99 : begin
            ap_NS_fsm = ap_ST_fsm_state100;
        end
        ap_ST_fsm_state100 : begin
            ap_NS_fsm = ap_ST_fsm_state101;
        end
        ap_ST_fsm_state101 : begin
            ap_NS_fsm = ap_ST_fsm_state102;
        end
        ap_ST_fsm_state102 : begin
            ap_NS_fsm = ap_ST_fsm_state103;
        end
        ap_ST_fsm_state103 : begin
            ap_NS_fsm = ap_ST_fsm_state104;
        end
        ap_ST_fsm_state104 : begin
            ap_NS_fsm = ap_ST_fsm_state105;
        end
        ap_ST_fsm_state105 : begin
            ap_NS_fsm = ap_ST_fsm_state106;
        end
        ap_ST_fsm_state106 : begin
            ap_NS_fsm = ap_ST_fsm_state107;
        end
        ap_ST_fsm_state107 : begin
            ap_NS_fsm = ap_ST_fsm_state108;
        end
        ap_ST_fsm_state108 : begin
            ap_NS_fsm = ap_ST_fsm_state109;
        end
        ap_ST_fsm_state109 : begin
            ap_NS_fsm = ap_ST_fsm_state110;
        end
        ap_ST_fsm_state110 : begin
            ap_NS_fsm = ap_ST_fsm_state111;
        end
        ap_ST_fsm_state111 : begin
            ap_NS_fsm = ap_ST_fsm_state112;
        end
        ap_ST_fsm_state112 : begin
            ap_NS_fsm = ap_ST_fsm_state113;
        end
        ap_ST_fsm_state113 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state114 : begin
            if (((icmp_ln230_fu_383_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state114))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state115;
            end
        end
        ap_ST_fsm_state115 : begin
            ap_NS_fsm = ap_ST_fsm_state114;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln230_1_fu_431_p2 = (phi_urem_reg_228 + 14'd1);

assign add_ln233_fu_410_p2 = (29'd26215 + phi_mul_reg_216);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state113 = ap_CS_fsm[32'd112];

assign ap_CS_fsm_state114 = ap_CS_fsm[32'd113];

assign ap_CS_fsm_state115 = ap_CS_fsm[32'd114];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_block_state6_on_subcall_done = ((grp_decimation1_fu_264_ap_done == 1'b0) | (grp_fir_fu_256_ap_done == 1'b0));
end

assign ap_return = 32'd0;

assign dii_V_fu_288_p0 = y_I_d_V_q0;

assign dii_V_fu_288_p2 = ($signed(dii_V_fu_288_p0) - $signed(p_Val2_13_reg_174));

assign dqq_V_fu_294_p0 = y_Q_d_V_q0;

assign dqq_V_fu_294_p2 = ($signed(dqq_V_fu_294_p0) - $signed(p_Val2_15_reg_184));

assign grp_decimation1_fu_264_ap_start = grp_decimation1_fu_264_ap_start_reg;

assign grp_fir_fu_256_ap_start = grp_fir_fu_256_ap_start_reg;

assign grp_fu_366_p0 = {{ret_V_reg_516}, {32'd0}};

assign grp_shift_fu_240_ap_start = grp_shift_fu_240_ap_start_reg;

assign icmp_ln230_1_fu_437_p2 = ((add_ln230_1_fu_431_p2 < 14'd10) ? 1'b1 : 1'b0);

assign icmp_ln230_fu_383_p2 = ((n_0_i_reg_205 == 14'd12500) ? 1'b1 : 1'b0);

assign icmp_ln233_fu_404_p2 = ((trunc_ln233_fu_400_p1 == 4'd0) ? 1'b1 : 1'b0);

assign icmp_ln252_fu_270_p2 = ((q_0_i_reg_194 == 14'd12500) ? 1'b1 : 1'b0);

assign lhs_V_fu_342_p1 = $signed(r_V_8_fu_330_p2);

assign n_fu_389_p2 = (n_0_i_reg_205 + 14'd1);

assign q_fu_282_p2 = (q_0_i_reg_194 + 14'd1);

assign r_V_2_fu_312_p1 = ary_i_value_1_V_reg_500;

assign r_V_6_fu_306_p0 = dqq_V_reg_511;

assign r_V_6_fu_306_p1 = r_V_fu_300_p1;

assign r_V_6_fu_306_p2 = ($signed(r_V_6_fu_306_p0) * $signed(r_V_6_fu_306_p1));

assign r_V_7_fu_318_p0 = r_V_2_fu_312_p1;

assign r_V_7_fu_318_p1 = dii_V_reg_506;

assign r_V_7_fu_318_p2 = ($signed(r_V_7_fu_318_p0) * $signed(r_V_7_fu_318_p1));

assign r_V_8_fu_330_p0 = r_V_fu_300_p1;

assign r_V_8_fu_330_p1 = r_V_fu_300_p1;

assign r_V_8_fu_330_p2 = ($signed(r_V_8_fu_330_p0) * $signed(r_V_8_fu_330_p1));

assign r_V_9_fu_336_p0 = r_V_2_fu_312_p1;

assign r_V_9_fu_336_p1 = r_V_2_fu_312_p1;

assign r_V_9_fu_336_p2 = ($signed(r_V_9_fu_336_p0) * $signed(r_V_9_fu_336_p1));

assign r_V_fu_300_p1 = ary_r_value_1_V_reg_494;

assign ret_V_6_fu_350_p2 = ($signed(rhs_V_fu_346_p1) + $signed(lhs_V_fu_342_p1));

assign ret_V_fu_324_p2 = (r_V_6_fu_306_p2 - r_V_7_fu_318_p2);

assign rhs_V_fu_346_p1 = $signed(r_V_9_fu_336_p2);

assign select_ln230_fu_443_p3 = ((icmp_ln230_1_fu_437_p2[0:0] === 1'b1) ? add_ln230_1_fu_431_p2 : 14'd0);

assign tmp_14_fu_416_p4 = {{phi_mul_reg_216[28:18]}};

assign trunc_ln233_fu_400_p1 = phi_urem_reg_228[3:0];

assign y_I_V_address0 = grp_shift_fu_240_ary_r_V_address0;

assign y_I_V_ce0 = grp_shift_fu_240_ary_r_V_ce0;

assign y_Q_V_address0 = grp_shift_fu_240_ary_i_V_address0;

assign y_Q_V_ce0 = grp_shift_fu_240_ary_i_V_ce0;

assign y_demod_d_V_address0 = zext_ln236_fu_426_p1;

assign y_demod_d_V_d0 = y_demod_nd_V_q0;

assign zext_ln232_fu_395_p1 = n_0_i_reg_205;

assign zext_ln236_fu_426_p1 = tmp_14_fu_416_p4;

assign zext_ln255_fu_276_p1 = q_0_i_reg_194;

always @ (posedge ap_clk) begin
    zext_ln255_reg_474[63:14] <= 50'b00000000000000000000000000000000000000000000000000;
end

endmodule //demodulationFM
