-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
-- Version: 2019.2
-- Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity shift is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    ary_r_V_address0 : OUT STD_LOGIC_VECTOR (16 downto 0);
    ary_r_V_ce0 : OUT STD_LOGIC;
    ary_r_V_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    ary_i_V_address0 : OUT STD_LOGIC_VECTOR (16 downto 0);
    ary_i_V_ce0 : OUT STD_LOGIC;
    ary_i_V_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    ary_r_s_V_address0 : OUT STD_LOGIC_VECTOR (16 downto 0);
    ary_r_s_V_ce0 : OUT STD_LOGIC;
    ary_r_s_V_we0 : OUT STD_LOGIC;
    ary_r_s_V_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ary_i_s_V_address0 : OUT STD_LOGIC_VECTOR (16 downto 0);
    ary_i_s_V_ce0 : OUT STD_LOGIC;
    ary_i_s_V_we0 : OUT STD_LOGIC;
    ary_i_s_V_d0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of shift is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (6 downto 0) := "0000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (6 downto 0) := "0000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (6 downto 0) := "0001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (6 downto 0) := "0010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (6 downto 0) := "0100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (6 downto 0) := "1000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_FFEDC5D6 : STD_LOGIC_VECTOR (31 downto 0) := "11111111111011011100010111010110";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv17_0 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000000000";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv16_41 : STD_LOGIC_VECTOR (15 downto 0) := "0000000001000001";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv9_1 : STD_LOGIC_VECTOR (8 downto 0) := "000000001";
    constant ap_const_lv9_0 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    constant ap_const_lv16_C0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000011000000";
    constant ap_const_lv17_186A0 : STD_LOGIC_VECTOR (16 downto 0) := "11000011010100000";
    constant ap_const_lv17_1 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000000001";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv41_123A2900 : STD_LOGIC_VECTOR (40 downto 0) := "00000000000010010001110100010100100000000";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_27 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100111";
    constant ap_const_lv32_1000000 : STD_LOGIC_VECTOR (31 downto 0) := "00000001000000000000000000000000";
    constant ap_const_lv32_FF000000 : STD_LOGIC_VECTOR (31 downto 0) := "11111111000000000000000000000000";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv16_1 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000001";
    constant ap_const_lv16_100 : STD_LOGIC_VECTOR (15 downto 0) := "0000000100000000";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv7_40 : STD_LOGIC_VECTOR (6 downto 0) := "1000000";
    constant ap_const_lv16_40 : STD_LOGIC_VECTOR (15 downto 0) := "0000000001000000";
    constant ap_const_boolean_1 : BOOLEAN := true;

    signal ap_CS_fsm : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal cos_table_address0 : STD_LOGIC_VECTOR (6 downto 0);
    signal cos_table_ce0 : STD_LOGIC;
    signal cos_table_q0 : STD_LOGIC_VECTOR (8 downto 0);
    signal sin_table_address0 : STD_LOGIC_VECTOR (6 downto 0);
    signal sin_table_ce0 : STD_LOGIC;
    signal sin_table_q0 : STD_LOGIC_VECTOR (8 downto 0);
    signal m_fu_389_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal m_reg_810 : STD_LOGIC_VECTOR (16 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal value_V_4_fu_435_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal value_V_4_reg_815 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln161_fu_383_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln850_fu_485_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln850_reg_820 : STD_LOGIC_VECTOR (15 downto 0);
    signal idx_1_fu_493_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal idx_1_reg_840 : STD_LOGIC_VECTOR (5 downto 0);
    signal zext_ln189_fu_497_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln189_reg_850 : STD_LOGIC_VECTOR (63 downto 0);
    signal value_r_V_reg_870 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal value_i_V_reg_875 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln96_fu_503_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln96_reg_880 : STD_LOGIC_VECTOR (0 downto 0);
    signal sext_ln1118_fu_620_p1 : STD_LOGIC_VECTOR (39 downto 0);
    signal sext_ln1118_reg_898 : STD_LOGIC_VECTOR (39 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal sext_ln1118_1_fu_623_p1 : STD_LOGIC_VECTOR (39 downto 0);
    signal sext_ln1118_1_reg_904 : STD_LOGIC_VECTOR (39 downto 0);
    signal p_Val2_6_fu_731_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal p_Val2_6_reg_924 : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal real_V_reg_929 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal imag_V_reg_935 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln193_fu_797_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln193_reg_941 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln198_fu_802_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln198_reg_945 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Val2_s_reg_206 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal m_0_reg_217 : STD_LOGIC_VECTOR (16 downto 0);
    signal zext_ln105_1_fu_596_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_mux_idx_3_i_phi_fu_231_p10 : STD_LOGIC_VECTOR (15 downto 0);
    signal and_ln100_fu_521_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_fu_339_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln109_fu_583_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_365_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln113_fu_578_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal sign_3_i_reg_244 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln70_1_fu_715_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_mux_idx_3_i2_phi_fu_269_p10 : STD_LOGIC_VECTOR (15 downto 0);
    signal and_ln65_fu_640_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln74_fu_702_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln78_fu_697_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal sign_3_i3_reg_282 : STD_LOGIC_VECTOR (0 downto 0);
    signal sext_ln1265_fu_601_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal sext_ln1265_1_fu_720_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ary_r_s_V_addr_1_gep_fu_174_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal ary_i_s_V_addr_1_gep_fu_182_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal ary_r_s_V_addr_gep_fu_190_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal ary_i_s_V_addr_gep_fu_198_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal grp_fu_371_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_377_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_309_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_fu_324_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal grp_fu_318_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_fu_333_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_fu_345_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal grp_fu_354_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_fu_360_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal lhs_V_fu_395_p3 : STD_LOGIC_VECTOR (39 downto 0);
    signal zext_ln728_fu_403_p1 : STD_LOGIC_VECTOR (40 downto 0);
    signal add_ln1192_fu_407_p2 : STD_LOGIC_VECTOR (40 downto 0);
    signal value_V_3_fu_413_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln1494_fu_423_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal value_V_fu_429_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln851_fu_461_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal ret_V_fu_443_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln851_fu_465_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ret_V_1_fu_471_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_Result_s_fu_453_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln851_fu_477_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_fu_508_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_fu_304_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln100_fu_515_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln113_fu_534_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal sub_ln113_fu_537_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_6_fu_543_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_5_fu_527_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal sub_ln113_1_fu_551_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_3_fu_557_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal select_ln113_fu_564_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal idx_2_fu_572_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal zext_ln105_fu_587_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal idx_fu_590_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal sub_ln703_4_fu_606_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal p_Val2_4_fu_612_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_8_fu_627_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln65_fu_634_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln78_fu_653_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal sub_ln78_fu_656_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_13_fu_662_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_12_fu_646_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal sub_ln78_1_fu_670_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_7_fu_676_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal select_ln78_fu_683_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal idx_4_fu_691_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal zext_ln70_fu_706_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal idx_3_fu_709_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal sub_ln703_5_fu_725_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal mul_ln700_fu_745_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln700_fu_745_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal mul_ln1192_fu_749_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln1118_2_fu_739_p1 : STD_LOGIC_VECTOR (39 downto 0);
    signal mul_ln1192_fu_749_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal sext_ln1118_3_fu_742_p1 : STD_LOGIC_VECTOR (39 downto 0);
    signal mul_ln700_fu_745_p2 : STD_LOGIC_VECTOR (39 downto 0);
    signal mul_ln1192_fu_749_p2 : STD_LOGIC_VECTOR (39 downto 0);
    signal ret_V_4_fu_755_p2 : STD_LOGIC_VECTOR (39 downto 0);
    signal mul_ln700_1_fu_771_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln700_1_fu_771_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal mul_ln1193_fu_776_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln1193_fu_776_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal mul_ln700_1_fu_771_p2 : STD_LOGIC_VECTOR (39 downto 0);
    signal mul_ln1193_fu_776_p2 : STD_LOGIC_VECTOR (39 downto 0);
    signal ret_V_5_fu_781_p2 : STD_LOGIC_VECTOR (39 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_condition_188 : BOOLEAN;
    signal ap_condition_192 : BOOLEAN;
    signal ap_condition_195 : BOOLEAN;
    signal ap_condition_157 : BOOLEAN;
    signal ap_condition_164 : BOOLEAN;
    signal ap_condition_168 : BOOLEAN;

    component shift_cos_table IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (6 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (8 downto 0) );
    end component;


    component shift_sin_table IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (6 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (8 downto 0) );
    end component;



begin
    cos_table_U : component shift_cos_table
    generic map (
        DataWidth => 9,
        AddressRange => 65,
        AddressWidth => 7)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => cos_table_address0,
        ce0 => cos_table_ce0,
        q0 => cos_table_q0);

    sin_table_U : component shift_sin_table
    generic map (
        DataWidth => 9,
        AddressRange => 65,
        AddressWidth => 7)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => sin_table_address0,
        ce0 => sin_table_ce0,
        q0 => sin_table_q0);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    m_0_reg_217_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
                m_0_reg_217 <= m_reg_810;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                m_0_reg_217 <= ap_const_lv17_0;
            end if; 
        end if;
    end process;

    p_Val2_s_reg_206_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
                p_Val2_s_reg_206 <= value_V_4_reg_815;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                p_Val2_s_reg_206 <= ap_const_lv32_FFEDC5D6;
            end if; 
        end if;
    end process;

    sign_3_i3_reg_282_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((((icmp_ln96_reg_880 = ap_const_lv1_0) and (ap_const_lv1_0 = and_ln65_fu_640_p2) and (grp_fu_365_p2 = ap_const_lv1_0) and (grp_fu_339_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state4)) or ((icmp_ln96_reg_880 = ap_const_lv1_0) and (ap_const_lv1_0 = and_ln65_fu_640_p2) and (grp_fu_339_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state4) and (grp_fu_365_p2 = ap_const_lv1_1)))) then 
                sign_3_i3_reg_282 <= ap_const_lv1_1;
            elsif ((((icmp_ln96_reg_880 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state4)) or ((icmp_ln96_reg_880 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state4) and (ap_const_lv1_1 = and_ln65_fu_640_p2)) or ((icmp_ln96_reg_880 = ap_const_lv1_0) and (ap_const_lv1_0 = and_ln65_fu_640_p2) and (ap_const_logic_1 = ap_CS_fsm_state4) and (grp_fu_339_p2 = ap_const_lv1_1)))) then 
                sign_3_i3_reg_282 <= ap_const_lv1_0;
            end if; 
        end if;
    end process;

    sign_3_i_reg_244_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((((icmp_ln96_fu_503_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3)) or ((icmp_ln96_fu_503_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3) and (ap_const_lv1_1 = and_ln100_fu_521_p2)) or ((icmp_ln96_fu_503_p2 = ap_const_lv1_0) and (grp_fu_365_p2 = ap_const_lv1_0) and (grp_fu_339_p2 = ap_const_lv1_0) and (ap_const_lv1_0 = and_ln100_fu_521_p2) and (ap_const_logic_1 = ap_CS_fsm_state3)))) then 
                sign_3_i_reg_244 <= ap_const_lv1_0;
            elsif ((((icmp_ln96_fu_503_p2 = ap_const_lv1_0) and (grp_fu_339_p2 = ap_const_lv1_0) and (ap_const_lv1_0 = and_ln100_fu_521_p2) and (ap_const_logic_1 = ap_CS_fsm_state3) and (grp_fu_365_p2 = ap_const_lv1_1)) or ((icmp_ln96_fu_503_p2 = ap_const_lv1_0) and (ap_const_lv1_0 = and_ln100_fu_521_p2) and (ap_const_logic_1 = ap_CS_fsm_state3) and (grp_fu_339_p2 = ap_const_lv1_1)))) then 
                sign_3_i_reg_244 <= ap_const_lv1_1;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state6)) then
                icmp_ln193_reg_941 <= icmp_ln193_fu_797_p2;
                imag_V_reg_935 <= ret_V_5_fu_781_p2(39 downto 8);
                real_V_reg_929 <= ret_V_4_fu_755_p2(39 downto 8);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln193_fu_797_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state6))) then
                icmp_ln198_reg_945 <= icmp_ln198_fu_802_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                icmp_ln96_reg_880 <= icmp_ln96_fu_503_p2;
                value_i_V_reg_875 <= ary_i_V_q0;
                value_r_V_reg_870 <= ary_r_V_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln161_fu_383_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                idx_1_reg_840 <= idx_1_fu_493_p1;
                select_ln850_reg_820 <= select_ln850_fu_485_p3;
                value_V_4_reg_815 <= value_V_4_fu_435_p3;
                    zext_ln189_reg_850(16 downto 0) <= zext_ln189_fu_497_p1(16 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                m_reg_810 <= m_fu_389_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state5)) then
                p_Val2_6_reg_924 <= p_Val2_6_fu_731_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then
                sext_ln1118_1_reg_904 <= sext_ln1118_1_fu_623_p1;
                sext_ln1118_reg_898 <= sext_ln1118_fu_620_p1;
            end if;
        end if;
    end process;
    zext_ln189_reg_850(63 downto 17) <= "00000000000000000000000000000000000000000000000";

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state2, icmp_ln161_fu_383_p2)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((icmp_ln161_fu_383_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state2;
            when others =>  
                ap_NS_fsm <= "XXXXXXX";
        end case;
    end process;
    add_ln1192_fu_407_p2 <= std_logic_vector(unsigned(ap_const_lv41_123A2900) + unsigned(zext_ln728_fu_403_p1));
    and_ln100_fu_521_p2 <= (xor_ln100_fu_515_p2 and grp_fu_304_p2);
    and_ln65_fu_640_p2 <= (xor_ln65_fu_634_p2 and grp_fu_304_p2);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);

    ap_condition_157_assign_proc : process(icmp_ln96_fu_503_p2, and_ln100_fu_521_p2, grp_fu_339_p2)
    begin
                ap_condition_157 <= ((icmp_ln96_fu_503_p2 = ap_const_lv1_0) and (ap_const_lv1_0 = and_ln100_fu_521_p2) and (grp_fu_339_p2 = ap_const_lv1_1));
    end process;


    ap_condition_164_assign_proc : process(icmp_ln96_fu_503_p2, and_ln100_fu_521_p2, grp_fu_339_p2, grp_fu_365_p2)
    begin
                ap_condition_164 <= ((icmp_ln96_fu_503_p2 = ap_const_lv1_0) and (grp_fu_339_p2 = ap_const_lv1_0) and (ap_const_lv1_0 = and_ln100_fu_521_p2) and (grp_fu_365_p2 = ap_const_lv1_1));
    end process;


    ap_condition_168_assign_proc : process(icmp_ln96_fu_503_p2, and_ln100_fu_521_p2, grp_fu_339_p2, grp_fu_365_p2)
    begin
                ap_condition_168 <= ((icmp_ln96_fu_503_p2 = ap_const_lv1_0) and (grp_fu_365_p2 = ap_const_lv1_0) and (grp_fu_339_p2 = ap_const_lv1_0) and (ap_const_lv1_0 = and_ln100_fu_521_p2));
    end process;


    ap_condition_188_assign_proc : process(icmp_ln96_reg_880, grp_fu_339_p2, and_ln65_fu_640_p2)
    begin
                ap_condition_188 <= ((icmp_ln96_reg_880 = ap_const_lv1_0) and (ap_const_lv1_0 = and_ln65_fu_640_p2) and (grp_fu_339_p2 = ap_const_lv1_1));
    end process;


    ap_condition_192_assign_proc : process(icmp_ln96_reg_880, grp_fu_339_p2, grp_fu_365_p2, and_ln65_fu_640_p2)
    begin
                ap_condition_192 <= ((icmp_ln96_reg_880 = ap_const_lv1_0) and (ap_const_lv1_0 = and_ln65_fu_640_p2) and (grp_fu_339_p2 = ap_const_lv1_0) and (grp_fu_365_p2 = ap_const_lv1_1));
    end process;


    ap_condition_195_assign_proc : process(icmp_ln96_reg_880, grp_fu_339_p2, grp_fu_365_p2, and_ln65_fu_640_p2)
    begin
                ap_condition_195 <= ((icmp_ln96_reg_880 = ap_const_lv1_0) and (ap_const_lv1_0 = and_ln65_fu_640_p2) and (grp_fu_365_p2 = ap_const_lv1_0) and (grp_fu_339_p2 = ap_const_lv1_0));
    end process;


    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state2, icmp_ln161_fu_383_p2)
    begin
        if ((((icmp_ln161_fu_383_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2)) or ((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_phi_mux_idx_3_i2_phi_fu_269_p10_assign_proc : process(select_ln850_reg_820, icmp_ln96_reg_880, ap_CS_fsm_state4, zext_ln70_1_fu_715_p1, and_ln65_fu_640_p2, zext_ln74_fu_702_p1, zext_ln78_fu_697_p1, ap_condition_188, ap_condition_192, ap_condition_195)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then
            if (((icmp_ln96_reg_880 = ap_const_lv1_0) and (ap_const_lv1_1 = and_ln65_fu_640_p2))) then 
                ap_phi_mux_idx_3_i2_phi_fu_269_p10 <= select_ln850_reg_820;
            elsif ((icmp_ln96_reg_880 = ap_const_lv1_1)) then 
                ap_phi_mux_idx_3_i2_phi_fu_269_p10 <= ap_const_lv16_0;
            elsif ((ap_const_boolean_1 = ap_condition_195)) then 
                ap_phi_mux_idx_3_i2_phi_fu_269_p10 <= zext_ln78_fu_697_p1;
            elsif ((ap_const_boolean_1 = ap_condition_192)) then 
                ap_phi_mux_idx_3_i2_phi_fu_269_p10 <= zext_ln74_fu_702_p1;
            elsif ((ap_const_boolean_1 = ap_condition_188)) then 
                ap_phi_mux_idx_3_i2_phi_fu_269_p10 <= zext_ln70_1_fu_715_p1;
            else 
                ap_phi_mux_idx_3_i2_phi_fu_269_p10 <= "XXXXXXXXXXXXXXXX";
            end if;
        else 
            ap_phi_mux_idx_3_i2_phi_fu_269_p10 <= "XXXXXXXXXXXXXXXX";
        end if; 
    end process;


    ap_phi_mux_idx_3_i_phi_fu_231_p10_assign_proc : process(select_ln850_reg_820, ap_CS_fsm_state3, icmp_ln96_fu_503_p2, zext_ln105_1_fu_596_p1, and_ln100_fu_521_p2, zext_ln109_fu_583_p1, zext_ln113_fu_578_p1, ap_condition_157, ap_condition_164, ap_condition_168)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
            if (((icmp_ln96_fu_503_p2 = ap_const_lv1_0) and (ap_const_lv1_1 = and_ln100_fu_521_p2))) then 
                ap_phi_mux_idx_3_i_phi_fu_231_p10 <= select_ln850_reg_820;
            elsif ((icmp_ln96_fu_503_p2 = ap_const_lv1_1)) then 
                ap_phi_mux_idx_3_i_phi_fu_231_p10 <= ap_const_lv16_0;
            elsif ((ap_const_boolean_1 = ap_condition_168)) then 
                ap_phi_mux_idx_3_i_phi_fu_231_p10 <= zext_ln113_fu_578_p1;
            elsif ((ap_const_boolean_1 = ap_condition_164)) then 
                ap_phi_mux_idx_3_i_phi_fu_231_p10 <= zext_ln109_fu_583_p1;
            elsif ((ap_const_boolean_1 = ap_condition_157)) then 
                ap_phi_mux_idx_3_i_phi_fu_231_p10 <= zext_ln105_1_fu_596_p1;
            else 
                ap_phi_mux_idx_3_i_phi_fu_231_p10 <= "XXXXXXXXXXXXXXXX";
            end if;
        else 
            ap_phi_mux_idx_3_i_phi_fu_231_p10 <= "XXXXXXXXXXXXXXXX";
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state2, icmp_ln161_fu_383_p2)
    begin
        if (((icmp_ln161_fu_383_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    ary_i_V_address0 <= zext_ln189_fu_497_p1(17 - 1 downto 0);

    ary_i_V_ce0_assign_proc : process(ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            ary_i_V_ce0 <= ap_const_logic_1;
        else 
            ary_i_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    ary_i_s_V_addr_1_gep_fu_182_p3 <= zext_ln189_reg_850(17 - 1 downto 0);
    ary_i_s_V_addr_gep_fu_198_p3 <= zext_ln189_reg_850(17 - 1 downto 0);

    ary_i_s_V_address0_assign_proc : process(zext_ln189_reg_850, icmp_ln193_reg_941, icmp_ln198_reg_945, ap_CS_fsm_state7, ary_i_s_V_addr_1_gep_fu_182_p3, ary_i_s_V_addr_gep_fu_198_p3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then
            if ((icmp_ln193_reg_941 = ap_const_lv1_1)) then 
                ary_i_s_V_address0 <= ary_i_s_V_addr_gep_fu_198_p3;
            elsif (((icmp_ln193_reg_941 = ap_const_lv1_0) and (icmp_ln198_reg_945 = ap_const_lv1_1))) then 
                ary_i_s_V_address0 <= ary_i_s_V_addr_1_gep_fu_182_p3;
            elsif (((icmp_ln198_reg_945 = ap_const_lv1_0) and (icmp_ln193_reg_941 = ap_const_lv1_0))) then 
                ary_i_s_V_address0 <= zext_ln189_reg_850(17 - 1 downto 0);
            else 
                ary_i_s_V_address0 <= "XXXXXXXXXXXXXXXXX";
            end if;
        else 
            ary_i_s_V_address0 <= "XXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    ary_i_s_V_ce0_assign_proc : process(icmp_ln193_reg_941, icmp_ln198_reg_945, ap_CS_fsm_state7)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_state7) and (icmp_ln193_reg_941 = ap_const_lv1_1)) or ((icmp_ln193_reg_941 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state7) and (icmp_ln198_reg_945 = ap_const_lv1_1)) or ((icmp_ln198_reg_945 = ap_const_lv1_0) and (icmp_ln193_reg_941 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state7)))) then 
            ary_i_s_V_ce0 <= ap_const_logic_1;
        else 
            ary_i_s_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    ary_i_s_V_d0_assign_proc : process(imag_V_reg_935, icmp_ln193_reg_941, icmp_ln198_reg_945, ap_CS_fsm_state7, grp_fu_377_p2)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_state7) and (icmp_ln193_reg_941 = ap_const_lv1_1)) or ((icmp_ln193_reg_941 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state7) and (icmp_ln198_reg_945 = ap_const_lv1_1)))) then 
            ary_i_s_V_d0 <= grp_fu_377_p2;
        elsif (((icmp_ln198_reg_945 = ap_const_lv1_0) and (icmp_ln193_reg_941 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state7))) then 
            ary_i_s_V_d0 <= imag_V_reg_935;
        else 
            ary_i_s_V_d0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    ary_i_s_V_we0_assign_proc : process(icmp_ln193_reg_941, icmp_ln198_reg_945, ap_CS_fsm_state7)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_state7) and (icmp_ln193_reg_941 = ap_const_lv1_1)) or ((icmp_ln193_reg_941 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state7) and (icmp_ln198_reg_945 = ap_const_lv1_1)) or ((icmp_ln198_reg_945 = ap_const_lv1_0) and (icmp_ln193_reg_941 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state7)))) then 
            ary_i_s_V_we0 <= ap_const_logic_1;
        else 
            ary_i_s_V_we0 <= ap_const_logic_0;
        end if; 
    end process;

    ary_r_V_address0 <= zext_ln189_fu_497_p1(17 - 1 downto 0);

    ary_r_V_ce0_assign_proc : process(ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            ary_r_V_ce0 <= ap_const_logic_1;
        else 
            ary_r_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    ary_r_s_V_addr_1_gep_fu_174_p3 <= zext_ln189_reg_850(17 - 1 downto 0);
    ary_r_s_V_addr_gep_fu_190_p3 <= zext_ln189_reg_850(17 - 1 downto 0);

    ary_r_s_V_address0_assign_proc : process(zext_ln189_reg_850, icmp_ln193_reg_941, icmp_ln198_reg_945, ap_CS_fsm_state7, ary_r_s_V_addr_1_gep_fu_174_p3, ary_r_s_V_addr_gep_fu_190_p3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then
            if ((icmp_ln193_reg_941 = ap_const_lv1_1)) then 
                ary_r_s_V_address0 <= ary_r_s_V_addr_gep_fu_190_p3;
            elsif (((icmp_ln193_reg_941 = ap_const_lv1_0) and (icmp_ln198_reg_945 = ap_const_lv1_1))) then 
                ary_r_s_V_address0 <= ary_r_s_V_addr_1_gep_fu_174_p3;
            elsif (((icmp_ln198_reg_945 = ap_const_lv1_0) and (icmp_ln193_reg_941 = ap_const_lv1_0))) then 
                ary_r_s_V_address0 <= zext_ln189_reg_850(17 - 1 downto 0);
            else 
                ary_r_s_V_address0 <= "XXXXXXXXXXXXXXXXX";
            end if;
        else 
            ary_r_s_V_address0 <= "XXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    ary_r_s_V_ce0_assign_proc : process(icmp_ln193_reg_941, icmp_ln198_reg_945, ap_CS_fsm_state7)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_state7) and (icmp_ln193_reg_941 = ap_const_lv1_1)) or ((icmp_ln193_reg_941 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state7) and (icmp_ln198_reg_945 = ap_const_lv1_1)) or ((icmp_ln198_reg_945 = ap_const_lv1_0) and (icmp_ln193_reg_941 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state7)))) then 
            ary_r_s_V_ce0 <= ap_const_logic_1;
        else 
            ary_r_s_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    ary_r_s_V_d0_assign_proc : process(real_V_reg_929, icmp_ln193_reg_941, icmp_ln198_reg_945, ap_CS_fsm_state7, grp_fu_371_p2)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_state7) and (icmp_ln193_reg_941 = ap_const_lv1_1)) or ((icmp_ln193_reg_941 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state7) and (icmp_ln198_reg_945 = ap_const_lv1_1)))) then 
            ary_r_s_V_d0 <= grp_fu_371_p2;
        elsif (((icmp_ln198_reg_945 = ap_const_lv1_0) and (icmp_ln193_reg_941 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state7))) then 
            ary_r_s_V_d0 <= real_V_reg_929;
        else 
            ary_r_s_V_d0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    ary_r_s_V_we0_assign_proc : process(icmp_ln193_reg_941, icmp_ln198_reg_945, ap_CS_fsm_state7)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_state7) and (icmp_ln193_reg_941 = ap_const_lv1_1)) or ((icmp_ln193_reg_941 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state7) and (icmp_ln198_reg_945 = ap_const_lv1_1)) or ((icmp_ln198_reg_945 = ap_const_lv1_0) and (icmp_ln193_reg_941 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state7)))) then 
            ary_r_s_V_we0 <= ap_const_logic_1;
        else 
            ary_r_s_V_we0 <= ap_const_logic_0;
        end if; 
    end process;

    cos_table_address0 <= sext_ln1265_fu_601_p1(7 - 1 downto 0);

    cos_table_ce0_assign_proc : process(ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            cos_table_ce0 <= ap_const_logic_1;
        else 
            cos_table_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_304_p2 <= "1" when (signed(select_ln850_reg_820) < signed(ap_const_lv16_41)) else "0";
    grp_fu_309_p4 <= select_ln850_reg_820(15 downto 6);
    grp_fu_318_p2 <= "1" when (signed(grp_fu_309_p4) > signed(ap_const_lv10_0)) else "0";
    grp_fu_324_p4 <= select_ln850_reg_820(15 downto 7);
    grp_fu_333_p2 <= "1" when (signed(grp_fu_324_p4) < signed(ap_const_lv9_1)) else "0";
    grp_fu_339_p2 <= (grp_fu_333_p2 and grp_fu_318_p2);
    grp_fu_345_p4 <= select_ln850_reg_820(15 downto 7);
    grp_fu_354_p2 <= "1" when (signed(grp_fu_345_p4) > signed(ap_const_lv9_0)) else "0";
    grp_fu_360_p2 <= "1" when (signed(select_ln850_reg_820) < signed(ap_const_lv16_C0)) else "0";
    grp_fu_365_p2 <= (grp_fu_360_p2 and grp_fu_354_p2);
    grp_fu_371_p2 <= std_logic_vector(unsigned(ap_const_lv32_0) - unsigned(real_V_reg_929));
    grp_fu_377_p2 <= std_logic_vector(unsigned(ap_const_lv32_0) - unsigned(imag_V_reg_935));
    icmp_ln1494_fu_423_p2 <= "1" when (signed(value_V_3_fu_413_p4) > signed(ap_const_lv32_1000000)) else "0";
    icmp_ln161_fu_383_p2 <= "1" when (m_0_reg_217 = ap_const_lv17_186A0) else "0";
    icmp_ln193_fu_797_p2 <= "1" when (select_ln850_reg_820 = ap_const_lv16_0) else "0";
    icmp_ln198_fu_802_p2 <= "1" when (select_ln850_reg_820 = ap_const_lv16_40) else "0";
    icmp_ln851_fu_465_p2 <= "1" when (trunc_ln851_fu_461_p1 = ap_const_lv16_0) else "0";
    icmp_ln96_fu_503_p2 <= "1" when (select_ln850_reg_820 = ap_const_lv16_100) else "0";
    idx_1_fu_493_p1 <= select_ln850_fu_485_p3(6 - 1 downto 0);
    idx_2_fu_572_p2 <= std_logic_vector(signed(ap_const_lv7_40) - signed(select_ln113_fu_564_p3));
    idx_3_fu_709_p2 <= std_logic_vector(signed(ap_const_lv7_40) - signed(zext_ln70_fu_706_p1));
    idx_4_fu_691_p2 <= std_logic_vector(signed(ap_const_lv7_40) - signed(select_ln78_fu_683_p3));
    idx_fu_590_p2 <= std_logic_vector(signed(ap_const_lv7_40) - signed(zext_ln105_fu_587_p1));
    lhs_V_fu_395_p3 <= (p_Val2_s_reg_206 & ap_const_lv8_0);
    m_fu_389_p2 <= std_logic_vector(unsigned(m_0_reg_217) + unsigned(ap_const_lv17_1));
    mul_ln1192_fu_749_p0 <= sext_ln1118_2_fu_739_p1(32 - 1 downto 0);
    mul_ln1192_fu_749_p1 <= sext_ln1118_3_fu_742_p1(9 - 1 downto 0);
    mul_ln1192_fu_749_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed(mul_ln1192_fu_749_p0) * signed(mul_ln1192_fu_749_p1))), 40));
    mul_ln1193_fu_776_p0 <= sext_ln1118_reg_898(32 - 1 downto 0);
    mul_ln1193_fu_776_p1 <= sext_ln1118_3_fu_742_p1(9 - 1 downto 0);
    mul_ln1193_fu_776_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed(mul_ln1193_fu_776_p0) * signed(mul_ln1193_fu_776_p1))), 40));
    mul_ln700_1_fu_771_p0 <= sext_ln1118_2_fu_739_p1(32 - 1 downto 0);
    mul_ln700_1_fu_771_p1 <= sext_ln1118_1_reg_904(9 - 1 downto 0);
    mul_ln700_1_fu_771_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed(mul_ln700_1_fu_771_p0) * signed(mul_ln700_1_fu_771_p1))), 40));
    mul_ln700_fu_745_p0 <= sext_ln1118_reg_898(32 - 1 downto 0);
    mul_ln700_fu_745_p1 <= sext_ln1118_1_reg_904(9 - 1 downto 0);
    mul_ln700_fu_745_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed(mul_ln700_fu_745_p0) * signed(mul_ln700_fu_745_p1))), 40));
    p_Result_s_fu_453_p3 <= value_V_4_fu_435_p3(31 downto 31);
    p_Val2_4_fu_612_p3 <= 
        sub_ln703_4_fu_606_p2 when (sign_3_i_reg_244(0) = '1') else 
        cos_table_q0;
    p_Val2_6_fu_731_p3 <= 
        sub_ln703_5_fu_725_p2 when (sign_3_i3_reg_282(0) = '1') else 
        sin_table_q0;
    ret_V_1_fu_471_p2 <= std_logic_vector(unsigned(ap_const_lv16_1) + unsigned(ret_V_fu_443_p4));
    ret_V_4_fu_755_p2 <= std_logic_vector(unsigned(mul_ln700_fu_745_p2) + unsigned(mul_ln1192_fu_749_p2));
    ret_V_5_fu_781_p2 <= std_logic_vector(unsigned(mul_ln700_1_fu_771_p2) - unsigned(mul_ln1193_fu_776_p2));
    ret_V_fu_443_p4 <= value_V_4_fu_435_p3(31 downto 16);
    select_ln113_fu_564_p3 <= 
        sub_ln113_1_fu_551_p2 when (tmp_5_fu_527_p3(0) = '1') else 
        tmp_3_fu_557_p3;
    select_ln78_fu_683_p3 <= 
        sub_ln78_1_fu_670_p2 when (tmp_12_fu_646_p3(0) = '1') else 
        tmp_7_fu_676_p3;
    select_ln850_fu_485_p3 <= 
        select_ln851_fu_477_p3 when (p_Result_s_fu_453_p3(0) = '1') else 
        ret_V_fu_443_p4;
    select_ln851_fu_477_p3 <= 
        ret_V_fu_443_p4 when (icmp_ln851_fu_465_p2(0) = '1') else 
        ret_V_1_fu_471_p2;
        sext_ln1118_1_fu_623_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(p_Val2_4_fu_612_p3),40));

        sext_ln1118_2_fu_739_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(value_i_V_reg_875),40));

        sext_ln1118_3_fu_742_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(p_Val2_6_reg_924),40));

        sext_ln1118_fu_620_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(value_r_V_reg_870),40));

        sext_ln1265_1_fu_720_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(ap_phi_mux_idx_3_i2_phi_fu_269_p10),64));

        sext_ln1265_fu_601_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(ap_phi_mux_idx_3_i_phi_fu_231_p10),64));

    sin_table_address0 <= sext_ln1265_1_fu_720_p1(7 - 1 downto 0);

    sin_table_ce0_assign_proc : process(ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            sin_table_ce0 <= ap_const_logic_1;
        else 
            sin_table_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    sub_ln113_1_fu_551_p2 <= std_logic_vector(unsigned(ap_const_lv7_0) - unsigned(tmp_6_fu_543_p3));
    sub_ln113_fu_537_p2 <= std_logic_vector(unsigned(ap_const_lv6_0) - unsigned(trunc_ln113_fu_534_p1));
    sub_ln703_4_fu_606_p2 <= std_logic_vector(unsigned(ap_const_lv9_0) - unsigned(cos_table_q0));
    sub_ln703_5_fu_725_p2 <= std_logic_vector(unsigned(ap_const_lv9_0) - unsigned(sin_table_q0));
    sub_ln78_1_fu_670_p2 <= std_logic_vector(unsigned(ap_const_lv7_0) - unsigned(tmp_13_fu_662_p3));
    sub_ln78_fu_656_p2 <= std_logic_vector(unsigned(ap_const_lv6_0) - unsigned(trunc_ln78_fu_653_p1));
    tmp_12_fu_646_p3 <= select_ln850_reg_820(15 downto 15);
    tmp_13_fu_662_p3 <= (ap_const_lv1_0 & sub_ln78_fu_656_p2);
    tmp_3_fu_557_p3 <= (ap_const_lv1_0 & idx_1_reg_840);
    tmp_5_fu_527_p3 <= select_ln850_reg_820(15 downto 15);
    tmp_6_fu_543_p3 <= (ap_const_lv1_0 & sub_ln113_fu_537_p2);
    tmp_7_fu_676_p3 <= (ap_const_lv1_0 & idx_1_reg_840);
    tmp_8_fu_627_p3 <= select_ln850_reg_820(15 downto 15);
    tmp_fu_508_p3 <= select_ln850_reg_820(15 downto 15);
    trunc_ln113_fu_534_p1 <= select_ln850_reg_820(6 - 1 downto 0);
    trunc_ln78_fu_653_p1 <= select_ln850_reg_820(6 - 1 downto 0);
    trunc_ln851_fu_461_p1 <= value_V_4_fu_435_p3(16 - 1 downto 0);
    value_V_3_fu_413_p4 <= add_ln1192_fu_407_p2(39 downto 8);
    value_V_4_fu_435_p3 <= 
        value_V_fu_429_p2 when (icmp_ln1494_fu_423_p2(0) = '1') else 
        value_V_3_fu_413_p4;
    value_V_fu_429_p2 <= std_logic_vector(signed(ap_const_lv32_FF000000) + signed(value_V_3_fu_413_p4));
    xor_ln100_fu_515_p2 <= (tmp_fu_508_p3 xor ap_const_lv1_1);
    xor_ln65_fu_634_p2 <= (tmp_8_fu_627_p3 xor ap_const_lv1_1);
    zext_ln105_1_fu_596_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(idx_fu_590_p2),16));
    zext_ln105_fu_587_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(idx_1_reg_840),7));
    zext_ln109_fu_583_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(idx_1_reg_840),16));
    zext_ln113_fu_578_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(idx_2_fu_572_p2),16));
    zext_ln189_fu_497_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(m_0_reg_217),64));
    zext_ln70_1_fu_715_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(idx_3_fu_709_p2),16));
    zext_ln70_fu_706_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(idx_1_reg_840),7));
    zext_ln728_fu_403_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(lhs_V_fu_395_p3),41));
    zext_ln74_fu_702_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(idx_1_reg_840),16));
    zext_ln78_fu_697_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(idx_4_fu_691_p2),16));
end behav;
