// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "shift.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic shift::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic shift::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<7> shift::ap_ST_fsm_state1 = "1";
const sc_lv<7> shift::ap_ST_fsm_state2 = "10";
const sc_lv<7> shift::ap_ST_fsm_state3 = "100";
const sc_lv<7> shift::ap_ST_fsm_state4 = "1000";
const sc_lv<7> shift::ap_ST_fsm_state5 = "10000";
const sc_lv<7> shift::ap_ST_fsm_state6 = "100000";
const sc_lv<7> shift::ap_ST_fsm_state7 = "1000000";
const sc_lv<32> shift::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> shift::ap_const_lv32_2 = "10";
const sc_lv<32> shift::ap_const_lv32_1 = "1";
const sc_lv<1> shift::ap_const_lv1_0 = "0";
const sc_lv<32> shift::ap_const_lv32_3 = "11";
const sc_lv<32> shift::ap_const_lv32_4 = "100";
const sc_lv<32> shift::ap_const_lv32_5 = "101";
const sc_lv<32> shift::ap_const_lv32_FFEDC5D6 = "11111111111011011100010111010110";
const sc_lv<32> shift::ap_const_lv32_6 = "110";
const sc_lv<17> shift::ap_const_lv17_0 = "00000000000000000";
const sc_lv<1> shift::ap_const_lv1_1 = "1";
const sc_lv<16> shift::ap_const_lv16_0 = "0000000000000000";
const sc_lv<16> shift::ap_const_lv16_41 = "1000001";
const sc_lv<32> shift::ap_const_lv32_F = "1111";
const sc_lv<10> shift::ap_const_lv10_0 = "0000000000";
const sc_lv<32> shift::ap_const_lv32_7 = "111";
const sc_lv<9> shift::ap_const_lv9_1 = "1";
const sc_lv<9> shift::ap_const_lv9_0 = "000000000";
const sc_lv<16> shift::ap_const_lv16_C0 = "11000000";
const sc_lv<17> shift::ap_const_lv17_186A0 = "11000011010100000";
const sc_lv<17> shift::ap_const_lv17_1 = "1";
const sc_lv<8> shift::ap_const_lv8_0 = "00000000";
const sc_lv<41> shift::ap_const_lv41_123A2900 = "10010001110100010100100000000";
const sc_lv<32> shift::ap_const_lv32_8 = "1000";
const sc_lv<32> shift::ap_const_lv32_27 = "100111";
const sc_lv<32> shift::ap_const_lv32_1000000 = "1000000000000000000000000";
const sc_lv<32> shift::ap_const_lv32_FF000000 = "11111111000000000000000000000000";
const sc_lv<32> shift::ap_const_lv32_10 = "10000";
const sc_lv<32> shift::ap_const_lv32_1F = "11111";
const sc_lv<16> shift::ap_const_lv16_1 = "1";
const sc_lv<16> shift::ap_const_lv16_100 = "100000000";
const sc_lv<6> shift::ap_const_lv6_0 = "000000";
const sc_lv<7> shift::ap_const_lv7_0 = "0000000";
const sc_lv<7> shift::ap_const_lv7_40 = "1000000";
const sc_lv<16> shift::ap_const_lv16_40 = "1000000";
const bool shift::ap_const_boolean_1 = true;

shift::shift(sc_module_name name) : sc_module(name), mVcdFile(0) {
    cos_table_U = new shift_cos_table("cos_table_U");
    cos_table_U->clk(ap_clk);
    cos_table_U->reset(ap_rst);
    cos_table_U->address0(cos_table_address0);
    cos_table_U->ce0(cos_table_ce0);
    cos_table_U->q0(cos_table_q0);
    sin_table_U = new shift_sin_table("sin_table_U");
    sin_table_U->clk(ap_clk);
    sin_table_U->reset(ap_rst);
    sin_table_U->address0(sin_table_address0);
    sin_table_U->ce0(sin_table_ce0);
    sin_table_U->q0(sin_table_q0);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_add_ln1192_fu_402_p2);
    sensitive << ( zext_ln728_fu_398_p1 );

    SC_METHOD(thread_and_ln100_fu_514_p2);
    sensitive << ( grp_fu_299_p2 );
    sensitive << ( xor_ln100_fu_508_p2 );

    SC_METHOD(thread_and_ln65_fu_633_p2);
    sensitive << ( grp_fu_299_p2 );
    sensitive << ( xor_ln65_fu_627_p2 );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state5);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state6);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state7);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_state3);
    sensitive << ( ary_r_V_empty_n );
    sensitive << ( ary_i_V_empty_n );

    SC_METHOD(thread_ap_condition_159);
    sensitive << ( icmp_ln96_fu_496_p2 );
    sensitive << ( and_ln100_fu_514_p2 );
    sensitive << ( grp_fu_334_p2 );

    SC_METHOD(thread_ap_condition_167);
    sensitive << ( icmp_ln96_fu_496_p2 );
    sensitive << ( and_ln100_fu_514_p2 );
    sensitive << ( grp_fu_334_p2 );
    sensitive << ( grp_fu_360_p2 );

    SC_METHOD(thread_ap_condition_172);
    sensitive << ( icmp_ln96_fu_496_p2 );
    sensitive << ( and_ln100_fu_514_p2 );
    sensitive << ( grp_fu_334_p2 );
    sensitive << ( grp_fu_360_p2 );

    SC_METHOD(thread_ap_condition_195);
    sensitive << ( icmp_ln96_reg_863 );
    sensitive << ( grp_fu_334_p2 );
    sensitive << ( and_ln65_fu_633_p2 );

    SC_METHOD(thread_ap_condition_199);
    sensitive << ( icmp_ln96_reg_863 );
    sensitive << ( grp_fu_334_p2 );
    sensitive << ( grp_fu_360_p2 );
    sensitive << ( and_ln65_fu_633_p2 );

    SC_METHOD(thread_ap_condition_202);
    sensitive << ( icmp_ln96_reg_863 );
    sensitive << ( grp_fu_334_p2 );
    sensitive << ( grp_fu_360_p2 );
    sensitive << ( and_ln65_fu_633_p2 );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln161_fu_378_p2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_phi_mux_idx_3_i2_phi_fu_264_p10);
    sensitive << ( select_ln850_reg_813 );
    sensitive << ( icmp_ln96_reg_863 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( zext_ln70_1_fu_708_p1 );
    sensitive << ( and_ln65_fu_633_p2 );
    sensitive << ( zext_ln74_fu_695_p1 );
    sensitive << ( zext_ln78_fu_690_p1 );
    sensitive << ( ap_condition_195 );
    sensitive << ( ap_condition_199 );
    sensitive << ( ap_condition_202 );

    SC_METHOD(thread_ap_phi_mux_idx_3_i_phi_fu_226_p10);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( select_ln850_reg_813 );
    sensitive << ( icmp_ln96_fu_496_p2 );
    sensitive << ( zext_ln105_1_fu_589_p1 );
    sensitive << ( and_ln100_fu_514_p2 );
    sensitive << ( zext_ln109_fu_576_p1 );
    sensitive << ( zext_ln113_fu_571_p1 );
    sensitive << ( ap_condition_159 );
    sensitive << ( ap_condition_167 );
    sensitive << ( ap_condition_172 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln161_fu_378_p2 );

    SC_METHOD(thread_ary_i_V_blk_n);
    sensitive << ( ary_i_V_empty_n );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_ary_i_V_read);
    sensitive << ( ary_r_V_empty_n );
    sensitive << ( ary_i_V_empty_n );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_ary_i_s_V_addr_1_gep_fu_176_p3);
    sensitive << ( zext_ln189_reg_843 );
    sensitive << ( icmp_ln193_reg_924 );
    sensitive << ( icmp_ln198_reg_928 );
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_ary_i_s_V_addr_gep_fu_192_p3);
    sensitive << ( zext_ln189_reg_843 );
    sensitive << ( icmp_ln193_reg_924 );
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_ary_i_s_V_address0);
    sensitive << ( zext_ln189_reg_843 );
    sensitive << ( icmp_ln193_reg_924 );
    sensitive << ( icmp_ln198_reg_928 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ary_i_s_V_addr_1_gep_fu_176_p3 );
    sensitive << ( ary_i_s_V_addr_gep_fu_192_p3 );

    SC_METHOD(thread_ary_i_s_V_ce0);
    sensitive << ( icmp_ln193_reg_924 );
    sensitive << ( icmp_ln198_reg_928 );
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_ary_i_s_V_d0);
    sensitive << ( imag_V_reg_918 );
    sensitive << ( icmp_ln193_reg_924 );
    sensitive << ( icmp_ln198_reg_928 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( grp_fu_372_p2 );

    SC_METHOD(thread_ary_i_s_V_we0);
    sensitive << ( icmp_ln193_reg_924 );
    sensitive << ( icmp_ln198_reg_928 );
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_ary_r_V_blk_n);
    sensitive << ( ary_r_V_empty_n );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_ary_r_V_read);
    sensitive << ( ary_r_V_empty_n );
    sensitive << ( ary_i_V_empty_n );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_ary_r_s_V_addr_1_gep_fu_168_p3);
    sensitive << ( zext_ln189_reg_843 );
    sensitive << ( icmp_ln193_reg_924 );
    sensitive << ( icmp_ln198_reg_928 );
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_ary_r_s_V_addr_gep_fu_184_p3);
    sensitive << ( zext_ln189_reg_843 );
    sensitive << ( icmp_ln193_reg_924 );
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_ary_r_s_V_address0);
    sensitive << ( zext_ln189_reg_843 );
    sensitive << ( icmp_ln193_reg_924 );
    sensitive << ( icmp_ln198_reg_928 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ary_r_s_V_addr_1_gep_fu_168_p3 );
    sensitive << ( ary_r_s_V_addr_gep_fu_184_p3 );

    SC_METHOD(thread_ary_r_s_V_ce0);
    sensitive << ( icmp_ln193_reg_924 );
    sensitive << ( icmp_ln198_reg_928 );
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_ary_r_s_V_d0);
    sensitive << ( real_V_reg_912 );
    sensitive << ( icmp_ln193_reg_924 );
    sensitive << ( icmp_ln198_reg_928 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( grp_fu_366_p2 );

    SC_METHOD(thread_ary_r_s_V_we0);
    sensitive << ( icmp_ln193_reg_924 );
    sensitive << ( icmp_ln198_reg_928 );
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_cos_table_address0);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( sext_ln1265_fu_594_p1 );

    SC_METHOD(thread_cos_table_ce0);
    sensitive << ( ary_r_V_empty_n );
    sensitive << ( ary_i_V_empty_n );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_grp_fu_299_p2);
    sensitive << ( ary_r_V_empty_n );
    sensitive << ( ary_i_V_empty_n );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( select_ln850_reg_813 );
    sensitive << ( icmp_ln96_fu_496_p2 );
    sensitive << ( icmp_ln96_reg_863 );
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_grp_fu_304_p4);
    sensitive << ( select_ln850_reg_813 );

    SC_METHOD(thread_grp_fu_313_p2);
    sensitive << ( ary_r_V_empty_n );
    sensitive << ( ary_i_V_empty_n );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( icmp_ln96_fu_496_p2 );
    sensitive << ( icmp_ln96_reg_863 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( and_ln100_fu_514_p2 );
    sensitive << ( and_ln65_fu_633_p2 );
    sensitive << ( grp_fu_304_p4 );

    SC_METHOD(thread_grp_fu_319_p4);
    sensitive << ( select_ln850_reg_813 );

    SC_METHOD(thread_grp_fu_328_p2);
    sensitive << ( ary_r_V_empty_n );
    sensitive << ( ary_i_V_empty_n );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( icmp_ln96_fu_496_p2 );
    sensitive << ( icmp_ln96_reg_863 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( and_ln100_fu_514_p2 );
    sensitive << ( and_ln65_fu_633_p2 );
    sensitive << ( grp_fu_319_p4 );

    SC_METHOD(thread_grp_fu_334_p2);
    sensitive << ( grp_fu_313_p2 );
    sensitive << ( grp_fu_328_p2 );

    SC_METHOD(thread_grp_fu_340_p4);
    sensitive << ( select_ln850_reg_813 );

    SC_METHOD(thread_grp_fu_349_p2);
    sensitive << ( ary_r_V_empty_n );
    sensitive << ( ary_i_V_empty_n );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( icmp_ln96_fu_496_p2 );
    sensitive << ( icmp_ln96_reg_863 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( and_ln100_fu_514_p2 );
    sensitive << ( grp_fu_334_p2 );
    sensitive << ( and_ln65_fu_633_p2 );
    sensitive << ( grp_fu_340_p4 );

    SC_METHOD(thread_grp_fu_355_p2);
    sensitive << ( ary_r_V_empty_n );
    sensitive << ( ary_i_V_empty_n );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( select_ln850_reg_813 );
    sensitive << ( icmp_ln96_fu_496_p2 );
    sensitive << ( icmp_ln96_reg_863 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( and_ln100_fu_514_p2 );
    sensitive << ( grp_fu_334_p2 );
    sensitive << ( and_ln65_fu_633_p2 );

    SC_METHOD(thread_grp_fu_360_p2);
    sensitive << ( grp_fu_349_p2 );
    sensitive << ( grp_fu_355_p2 );

    SC_METHOD(thread_grp_fu_366_p2);
    sensitive << ( real_V_reg_912 );

    SC_METHOD(thread_grp_fu_372_p2);
    sensitive << ( imag_V_reg_918 );

    SC_METHOD(thread_icmp_ln1494_fu_418_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln161_fu_378_p2 );
    sensitive << ( value_V_3_fu_408_p4 );

    SC_METHOD(thread_icmp_ln161_fu_378_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( m_0_reg_211 );

    SC_METHOD(thread_icmp_ln193_fu_790_p2);
    sensitive << ( select_ln850_reg_813 );
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_icmp_ln198_fu_795_p2);
    sensitive << ( select_ln850_reg_813 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( icmp_ln193_fu_790_p2 );

    SC_METHOD(thread_icmp_ln851_fu_460_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln161_fu_378_p2 );
    sensitive << ( trunc_ln851_fu_456_p1 );

    SC_METHOD(thread_icmp_ln96_fu_496_p2);
    sensitive << ( ary_r_V_empty_n );
    sensitive << ( ary_i_V_empty_n );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( select_ln850_reg_813 );

    SC_METHOD(thread_idx_1_fu_488_p1);
    sensitive << ( select_ln850_fu_480_p3 );

    SC_METHOD(thread_idx_2_fu_565_p2);
    sensitive << ( select_ln113_fu_557_p3 );

    SC_METHOD(thread_idx_3_fu_702_p2);
    sensitive << ( zext_ln70_fu_699_p1 );

    SC_METHOD(thread_idx_4_fu_684_p2);
    sensitive << ( select_ln78_fu_676_p3 );

    SC_METHOD(thread_idx_fu_583_p2);
    sensitive << ( zext_ln105_fu_580_p1 );

    SC_METHOD(thread_lhs_V_fu_390_p3);
    sensitive << ( p_Val2_s_reg_200 );

    SC_METHOD(thread_m_fu_384_p2);
    sensitive << ( m_0_reg_211 );

    SC_METHOD(thread_mul_ln1192_fu_742_p0);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( sext_ln1118_2_fu_732_p1 );

    SC_METHOD(thread_mul_ln1192_fu_742_p1);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( sext_ln1118_3_fu_735_p1 );

    SC_METHOD(thread_mul_ln1192_fu_742_p2);
    sensitive << ( mul_ln1192_fu_742_p0 );
    sensitive << ( mul_ln1192_fu_742_p1 );

    SC_METHOD(thread_mul_ln1193_fu_769_p0);
    sensitive << ( sext_ln1118_reg_881 );
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_mul_ln1193_fu_769_p1);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( sext_ln1118_3_fu_735_p1 );

    SC_METHOD(thread_mul_ln1193_fu_769_p2);
    sensitive << ( mul_ln1193_fu_769_p0 );
    sensitive << ( mul_ln1193_fu_769_p1 );

    SC_METHOD(thread_mul_ln700_1_fu_764_p0);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( sext_ln1118_2_fu_732_p1 );

    SC_METHOD(thread_mul_ln700_1_fu_764_p1);
    sensitive << ( sext_ln1118_1_reg_887 );
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_mul_ln700_1_fu_764_p2);
    sensitive << ( mul_ln700_1_fu_764_p0 );
    sensitive << ( mul_ln700_1_fu_764_p1 );

    SC_METHOD(thread_mul_ln700_fu_738_p0);
    sensitive << ( sext_ln1118_reg_881 );
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_mul_ln700_fu_738_p1);
    sensitive << ( sext_ln1118_1_reg_887 );
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_mul_ln700_fu_738_p2);
    sensitive << ( mul_ln700_fu_738_p0 );
    sensitive << ( mul_ln700_fu_738_p1 );

    SC_METHOD(thread_p_Result_s_fu_448_p3);
    sensitive << ( value_V_4_fu_430_p3 );

    SC_METHOD(thread_p_Val2_4_fu_605_p3);
    sensitive << ( cos_table_q0 );
    sensitive << ( sign_3_i_reg_239 );
    sensitive << ( sub_ln703_4_fu_599_p2 );

    SC_METHOD(thread_p_Val2_6_fu_724_p3);
    sensitive << ( sin_table_q0 );
    sensitive << ( sign_3_i3_reg_277 );
    sensitive << ( sub_ln703_5_fu_718_p2 );

    SC_METHOD(thread_ret_V_1_fu_466_p2);
    sensitive << ( ret_V_fu_438_p4 );

    SC_METHOD(thread_ret_V_4_fu_748_p2);
    sensitive << ( mul_ln700_fu_738_p2 );
    sensitive << ( mul_ln1192_fu_742_p2 );

    SC_METHOD(thread_ret_V_5_fu_774_p2);
    sensitive << ( mul_ln700_1_fu_764_p2 );
    sensitive << ( mul_ln1193_fu_769_p2 );

    SC_METHOD(thread_ret_V_fu_438_p4);
    sensitive << ( value_V_4_fu_430_p3 );

    SC_METHOD(thread_select_ln113_fu_557_p3);
    sensitive << ( tmp_5_fu_520_p3 );
    sensitive << ( sub_ln113_1_fu_544_p2 );
    sensitive << ( tmp_3_fu_550_p3 );

    SC_METHOD(thread_select_ln78_fu_676_p3);
    sensitive << ( tmp_12_fu_639_p3 );
    sensitive << ( sub_ln78_1_fu_663_p2 );
    sensitive << ( tmp_7_fu_669_p3 );

    SC_METHOD(thread_select_ln850_fu_480_p3);
    sensitive << ( ret_V_fu_438_p4 );
    sensitive << ( p_Result_s_fu_448_p3 );
    sensitive << ( select_ln851_fu_472_p3 );

    SC_METHOD(thread_select_ln851_fu_472_p3);
    sensitive << ( ret_V_fu_438_p4 );
    sensitive << ( icmp_ln851_fu_460_p2 );
    sensitive << ( ret_V_1_fu_466_p2 );

    SC_METHOD(thread_sext_ln1118_1_fu_616_p1);
    sensitive << ( p_Val2_4_fu_605_p3 );

    SC_METHOD(thread_sext_ln1118_2_fu_732_p1);
    sensitive << ( value_i_V_reg_858 );

    SC_METHOD(thread_sext_ln1118_3_fu_735_p1);
    sensitive << ( p_Val2_6_reg_907 );

    SC_METHOD(thread_sext_ln1118_fu_613_p1);
    sensitive << ( value_r_V_reg_853 );

    SC_METHOD(thread_sext_ln1265_1_fu_713_p1);
    sensitive << ( ap_phi_mux_idx_3_i2_phi_fu_264_p10 );

    SC_METHOD(thread_sext_ln1265_fu_594_p1);
    sensitive << ( ap_phi_mux_idx_3_i_phi_fu_226_p10 );

    SC_METHOD(thread_sin_table_address0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( sext_ln1265_1_fu_713_p1 );

    SC_METHOD(thread_sin_table_ce0);
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_sub_ln113_1_fu_544_p2);
    sensitive << ( tmp_6_fu_536_p3 );

    SC_METHOD(thread_sub_ln113_fu_530_p2);
    sensitive << ( trunc_ln113_fu_527_p1 );

    SC_METHOD(thread_sub_ln703_4_fu_599_p2);
    sensitive << ( cos_table_q0 );

    SC_METHOD(thread_sub_ln703_5_fu_718_p2);
    sensitive << ( sin_table_q0 );

    SC_METHOD(thread_sub_ln78_1_fu_663_p2);
    sensitive << ( tmp_13_fu_655_p3 );

    SC_METHOD(thread_sub_ln78_fu_649_p2);
    sensitive << ( trunc_ln78_fu_646_p1 );

    SC_METHOD(thread_tmp_12_fu_639_p3);
    sensitive << ( select_ln850_reg_813 );

    SC_METHOD(thread_tmp_13_fu_655_p3);
    sensitive << ( sub_ln78_fu_649_p2 );

    SC_METHOD(thread_tmp_3_fu_550_p3);
    sensitive << ( idx_1_reg_833 );

    SC_METHOD(thread_tmp_5_fu_520_p3);
    sensitive << ( select_ln850_reg_813 );

    SC_METHOD(thread_tmp_6_fu_536_p3);
    sensitive << ( sub_ln113_fu_530_p2 );

    SC_METHOD(thread_tmp_7_fu_669_p3);
    sensitive << ( idx_1_reg_833 );

    SC_METHOD(thread_tmp_8_fu_620_p3);
    sensitive << ( select_ln850_reg_813 );

    SC_METHOD(thread_tmp_fu_501_p3);
    sensitive << ( select_ln850_reg_813 );

    SC_METHOD(thread_trunc_ln113_fu_527_p1);
    sensitive << ( select_ln850_reg_813 );

    SC_METHOD(thread_trunc_ln78_fu_646_p1);
    sensitive << ( select_ln850_reg_813 );

    SC_METHOD(thread_trunc_ln851_fu_456_p1);
    sensitive << ( value_V_4_fu_430_p3 );

    SC_METHOD(thread_value_V_3_fu_408_p4);
    sensitive << ( add_ln1192_fu_402_p2 );

    SC_METHOD(thread_value_V_4_fu_430_p3);
    sensitive << ( value_V_3_fu_408_p4 );
    sensitive << ( icmp_ln1494_fu_418_p2 );
    sensitive << ( value_V_fu_424_p2 );

    SC_METHOD(thread_value_V_fu_424_p2);
    sensitive << ( value_V_3_fu_408_p4 );

    SC_METHOD(thread_xor_ln100_fu_508_p2);
    sensitive << ( tmp_fu_501_p3 );

    SC_METHOD(thread_xor_ln65_fu_627_p2);
    sensitive << ( tmp_8_fu_620_p3 );

    SC_METHOD(thread_zext_ln105_1_fu_589_p1);
    sensitive << ( idx_fu_583_p2 );

    SC_METHOD(thread_zext_ln105_fu_580_p1);
    sensitive << ( idx_1_reg_833 );

    SC_METHOD(thread_zext_ln109_fu_576_p1);
    sensitive << ( idx_1_reg_833 );

    SC_METHOD(thread_zext_ln113_fu_571_p1);
    sensitive << ( idx_2_fu_565_p2 );

    SC_METHOD(thread_zext_ln189_fu_492_p1);
    sensitive << ( m_0_reg_211 );

    SC_METHOD(thread_zext_ln70_1_fu_708_p1);
    sensitive << ( idx_3_fu_702_p2 );

    SC_METHOD(thread_zext_ln70_fu_699_p1);
    sensitive << ( idx_1_reg_833 );

    SC_METHOD(thread_zext_ln728_fu_398_p1);
    sensitive << ( lhs_V_fu_390_p3 );

    SC_METHOD(thread_zext_ln74_fu_695_p1);
    sensitive << ( idx_1_reg_833 );

    SC_METHOD(thread_zext_ln78_fu_690_p1);
    sensitive << ( idx_4_fu_684_p2 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ary_r_V_empty_n );
    sensitive << ( ary_i_V_empty_n );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln161_fu_378_p2 );

    ap_CS_fsm = "0000001";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "shift_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, ary_r_V_dout, "(port)ary_r_V_dout");
    sc_trace(mVcdFile, ary_r_V_empty_n, "(port)ary_r_V_empty_n");
    sc_trace(mVcdFile, ary_r_V_read, "(port)ary_r_V_read");
    sc_trace(mVcdFile, ary_i_V_dout, "(port)ary_i_V_dout");
    sc_trace(mVcdFile, ary_i_V_empty_n, "(port)ary_i_V_empty_n");
    sc_trace(mVcdFile, ary_i_V_read, "(port)ary_i_V_read");
    sc_trace(mVcdFile, ary_r_s_V_address0, "(port)ary_r_s_V_address0");
    sc_trace(mVcdFile, ary_r_s_V_ce0, "(port)ary_r_s_V_ce0");
    sc_trace(mVcdFile, ary_r_s_V_we0, "(port)ary_r_s_V_we0");
    sc_trace(mVcdFile, ary_r_s_V_d0, "(port)ary_r_s_V_d0");
    sc_trace(mVcdFile, ary_i_s_V_address0, "(port)ary_i_s_V_address0");
    sc_trace(mVcdFile, ary_i_s_V_ce0, "(port)ary_i_s_V_ce0");
    sc_trace(mVcdFile, ary_i_s_V_we0, "(port)ary_i_s_V_we0");
    sc_trace(mVcdFile, ary_i_s_V_d0, "(port)ary_i_s_V_d0");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, cos_table_address0, "cos_table_address0");
    sc_trace(mVcdFile, cos_table_ce0, "cos_table_ce0");
    sc_trace(mVcdFile, cos_table_q0, "cos_table_q0");
    sc_trace(mVcdFile, sin_table_address0, "sin_table_address0");
    sc_trace(mVcdFile, sin_table_ce0, "sin_table_ce0");
    sc_trace(mVcdFile, sin_table_q0, "sin_table_q0");
    sc_trace(mVcdFile, ary_r_V_blk_n, "ary_r_V_blk_n");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, ary_i_V_blk_n, "ary_i_V_blk_n");
    sc_trace(mVcdFile, m_fu_384_p2, "m_fu_384_p2");
    sc_trace(mVcdFile, m_reg_803, "m_reg_803");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, value_V_4_fu_430_p3, "value_V_4_fu_430_p3");
    sc_trace(mVcdFile, value_V_4_reg_808, "value_V_4_reg_808");
    sc_trace(mVcdFile, icmp_ln161_fu_378_p2, "icmp_ln161_fu_378_p2");
    sc_trace(mVcdFile, select_ln850_fu_480_p3, "select_ln850_fu_480_p3");
    sc_trace(mVcdFile, select_ln850_reg_813, "select_ln850_reg_813");
    sc_trace(mVcdFile, idx_1_fu_488_p1, "idx_1_fu_488_p1");
    sc_trace(mVcdFile, idx_1_reg_833, "idx_1_reg_833");
    sc_trace(mVcdFile, zext_ln189_fu_492_p1, "zext_ln189_fu_492_p1");
    sc_trace(mVcdFile, zext_ln189_reg_843, "zext_ln189_reg_843");
    sc_trace(mVcdFile, ap_block_state3, "ap_block_state3");
    sc_trace(mVcdFile, value_r_V_reg_853, "value_r_V_reg_853");
    sc_trace(mVcdFile, value_i_V_reg_858, "value_i_V_reg_858");
    sc_trace(mVcdFile, icmp_ln96_fu_496_p2, "icmp_ln96_fu_496_p2");
    sc_trace(mVcdFile, icmp_ln96_reg_863, "icmp_ln96_reg_863");
    sc_trace(mVcdFile, sext_ln1118_fu_613_p1, "sext_ln1118_fu_613_p1");
    sc_trace(mVcdFile, sext_ln1118_reg_881, "sext_ln1118_reg_881");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, sext_ln1118_1_fu_616_p1, "sext_ln1118_1_fu_616_p1");
    sc_trace(mVcdFile, sext_ln1118_1_reg_887, "sext_ln1118_1_reg_887");
    sc_trace(mVcdFile, p_Val2_6_fu_724_p3, "p_Val2_6_fu_724_p3");
    sc_trace(mVcdFile, p_Val2_6_reg_907, "p_Val2_6_reg_907");
    sc_trace(mVcdFile, ap_CS_fsm_state5, "ap_CS_fsm_state5");
    sc_trace(mVcdFile, real_V_reg_912, "real_V_reg_912");
    sc_trace(mVcdFile, ap_CS_fsm_state6, "ap_CS_fsm_state6");
    sc_trace(mVcdFile, imag_V_reg_918, "imag_V_reg_918");
    sc_trace(mVcdFile, icmp_ln193_fu_790_p2, "icmp_ln193_fu_790_p2");
    sc_trace(mVcdFile, icmp_ln193_reg_924, "icmp_ln193_reg_924");
    sc_trace(mVcdFile, icmp_ln198_fu_795_p2, "icmp_ln198_fu_795_p2");
    sc_trace(mVcdFile, icmp_ln198_reg_928, "icmp_ln198_reg_928");
    sc_trace(mVcdFile, p_Val2_s_reg_200, "p_Val2_s_reg_200");
    sc_trace(mVcdFile, ap_CS_fsm_state7, "ap_CS_fsm_state7");
    sc_trace(mVcdFile, m_0_reg_211, "m_0_reg_211");
    sc_trace(mVcdFile, zext_ln105_1_fu_589_p1, "zext_ln105_1_fu_589_p1");
    sc_trace(mVcdFile, ap_phi_mux_idx_3_i_phi_fu_226_p10, "ap_phi_mux_idx_3_i_phi_fu_226_p10");
    sc_trace(mVcdFile, and_ln100_fu_514_p2, "and_ln100_fu_514_p2");
    sc_trace(mVcdFile, grp_fu_334_p2, "grp_fu_334_p2");
    sc_trace(mVcdFile, zext_ln109_fu_576_p1, "zext_ln109_fu_576_p1");
    sc_trace(mVcdFile, grp_fu_360_p2, "grp_fu_360_p2");
    sc_trace(mVcdFile, zext_ln113_fu_571_p1, "zext_ln113_fu_571_p1");
    sc_trace(mVcdFile, sign_3_i_reg_239, "sign_3_i_reg_239");
    sc_trace(mVcdFile, zext_ln70_1_fu_708_p1, "zext_ln70_1_fu_708_p1");
    sc_trace(mVcdFile, ap_phi_mux_idx_3_i2_phi_fu_264_p10, "ap_phi_mux_idx_3_i2_phi_fu_264_p10");
    sc_trace(mVcdFile, and_ln65_fu_633_p2, "and_ln65_fu_633_p2");
    sc_trace(mVcdFile, zext_ln74_fu_695_p1, "zext_ln74_fu_695_p1");
    sc_trace(mVcdFile, zext_ln78_fu_690_p1, "zext_ln78_fu_690_p1");
    sc_trace(mVcdFile, sign_3_i3_reg_277, "sign_3_i3_reg_277");
    sc_trace(mVcdFile, sext_ln1265_fu_594_p1, "sext_ln1265_fu_594_p1");
    sc_trace(mVcdFile, sext_ln1265_1_fu_713_p1, "sext_ln1265_1_fu_713_p1");
    sc_trace(mVcdFile, ary_r_s_V_addr_1_gep_fu_168_p3, "ary_r_s_V_addr_1_gep_fu_168_p3");
    sc_trace(mVcdFile, ary_i_s_V_addr_1_gep_fu_176_p3, "ary_i_s_V_addr_1_gep_fu_176_p3");
    sc_trace(mVcdFile, ary_r_s_V_addr_gep_fu_184_p3, "ary_r_s_V_addr_gep_fu_184_p3");
    sc_trace(mVcdFile, ary_i_s_V_addr_gep_fu_192_p3, "ary_i_s_V_addr_gep_fu_192_p3");
    sc_trace(mVcdFile, grp_fu_366_p2, "grp_fu_366_p2");
    sc_trace(mVcdFile, grp_fu_372_p2, "grp_fu_372_p2");
    sc_trace(mVcdFile, grp_fu_304_p4, "grp_fu_304_p4");
    sc_trace(mVcdFile, grp_fu_319_p4, "grp_fu_319_p4");
    sc_trace(mVcdFile, grp_fu_313_p2, "grp_fu_313_p2");
    sc_trace(mVcdFile, grp_fu_328_p2, "grp_fu_328_p2");
    sc_trace(mVcdFile, grp_fu_340_p4, "grp_fu_340_p4");
    sc_trace(mVcdFile, grp_fu_349_p2, "grp_fu_349_p2");
    sc_trace(mVcdFile, grp_fu_355_p2, "grp_fu_355_p2");
    sc_trace(mVcdFile, lhs_V_fu_390_p3, "lhs_V_fu_390_p3");
    sc_trace(mVcdFile, zext_ln728_fu_398_p1, "zext_ln728_fu_398_p1");
    sc_trace(mVcdFile, add_ln1192_fu_402_p2, "add_ln1192_fu_402_p2");
    sc_trace(mVcdFile, value_V_3_fu_408_p4, "value_V_3_fu_408_p4");
    sc_trace(mVcdFile, icmp_ln1494_fu_418_p2, "icmp_ln1494_fu_418_p2");
    sc_trace(mVcdFile, value_V_fu_424_p2, "value_V_fu_424_p2");
    sc_trace(mVcdFile, trunc_ln851_fu_456_p1, "trunc_ln851_fu_456_p1");
    sc_trace(mVcdFile, ret_V_fu_438_p4, "ret_V_fu_438_p4");
    sc_trace(mVcdFile, icmp_ln851_fu_460_p2, "icmp_ln851_fu_460_p2");
    sc_trace(mVcdFile, ret_V_1_fu_466_p2, "ret_V_1_fu_466_p2");
    sc_trace(mVcdFile, p_Result_s_fu_448_p3, "p_Result_s_fu_448_p3");
    sc_trace(mVcdFile, select_ln851_fu_472_p3, "select_ln851_fu_472_p3");
    sc_trace(mVcdFile, tmp_fu_501_p3, "tmp_fu_501_p3");
    sc_trace(mVcdFile, grp_fu_299_p2, "grp_fu_299_p2");
    sc_trace(mVcdFile, xor_ln100_fu_508_p2, "xor_ln100_fu_508_p2");
    sc_trace(mVcdFile, trunc_ln113_fu_527_p1, "trunc_ln113_fu_527_p1");
    sc_trace(mVcdFile, sub_ln113_fu_530_p2, "sub_ln113_fu_530_p2");
    sc_trace(mVcdFile, tmp_6_fu_536_p3, "tmp_6_fu_536_p3");
    sc_trace(mVcdFile, tmp_5_fu_520_p3, "tmp_5_fu_520_p3");
    sc_trace(mVcdFile, sub_ln113_1_fu_544_p2, "sub_ln113_1_fu_544_p2");
    sc_trace(mVcdFile, tmp_3_fu_550_p3, "tmp_3_fu_550_p3");
    sc_trace(mVcdFile, select_ln113_fu_557_p3, "select_ln113_fu_557_p3");
    sc_trace(mVcdFile, idx_2_fu_565_p2, "idx_2_fu_565_p2");
    sc_trace(mVcdFile, zext_ln105_fu_580_p1, "zext_ln105_fu_580_p1");
    sc_trace(mVcdFile, idx_fu_583_p2, "idx_fu_583_p2");
    sc_trace(mVcdFile, sub_ln703_4_fu_599_p2, "sub_ln703_4_fu_599_p2");
    sc_trace(mVcdFile, p_Val2_4_fu_605_p3, "p_Val2_4_fu_605_p3");
    sc_trace(mVcdFile, tmp_8_fu_620_p3, "tmp_8_fu_620_p3");
    sc_trace(mVcdFile, xor_ln65_fu_627_p2, "xor_ln65_fu_627_p2");
    sc_trace(mVcdFile, trunc_ln78_fu_646_p1, "trunc_ln78_fu_646_p1");
    sc_trace(mVcdFile, sub_ln78_fu_649_p2, "sub_ln78_fu_649_p2");
    sc_trace(mVcdFile, tmp_13_fu_655_p3, "tmp_13_fu_655_p3");
    sc_trace(mVcdFile, tmp_12_fu_639_p3, "tmp_12_fu_639_p3");
    sc_trace(mVcdFile, sub_ln78_1_fu_663_p2, "sub_ln78_1_fu_663_p2");
    sc_trace(mVcdFile, tmp_7_fu_669_p3, "tmp_7_fu_669_p3");
    sc_trace(mVcdFile, select_ln78_fu_676_p3, "select_ln78_fu_676_p3");
    sc_trace(mVcdFile, idx_4_fu_684_p2, "idx_4_fu_684_p2");
    sc_trace(mVcdFile, zext_ln70_fu_699_p1, "zext_ln70_fu_699_p1");
    sc_trace(mVcdFile, idx_3_fu_702_p2, "idx_3_fu_702_p2");
    sc_trace(mVcdFile, sub_ln703_5_fu_718_p2, "sub_ln703_5_fu_718_p2");
    sc_trace(mVcdFile, mul_ln700_fu_738_p0, "mul_ln700_fu_738_p0");
    sc_trace(mVcdFile, mul_ln700_fu_738_p1, "mul_ln700_fu_738_p1");
    sc_trace(mVcdFile, mul_ln1192_fu_742_p0, "mul_ln1192_fu_742_p0");
    sc_trace(mVcdFile, sext_ln1118_2_fu_732_p1, "sext_ln1118_2_fu_732_p1");
    sc_trace(mVcdFile, mul_ln1192_fu_742_p1, "mul_ln1192_fu_742_p1");
    sc_trace(mVcdFile, sext_ln1118_3_fu_735_p1, "sext_ln1118_3_fu_735_p1");
    sc_trace(mVcdFile, mul_ln700_fu_738_p2, "mul_ln700_fu_738_p2");
    sc_trace(mVcdFile, mul_ln1192_fu_742_p2, "mul_ln1192_fu_742_p2");
    sc_trace(mVcdFile, ret_V_4_fu_748_p2, "ret_V_4_fu_748_p2");
    sc_trace(mVcdFile, mul_ln700_1_fu_764_p0, "mul_ln700_1_fu_764_p0");
    sc_trace(mVcdFile, mul_ln700_1_fu_764_p1, "mul_ln700_1_fu_764_p1");
    sc_trace(mVcdFile, mul_ln1193_fu_769_p0, "mul_ln1193_fu_769_p0");
    sc_trace(mVcdFile, mul_ln1193_fu_769_p1, "mul_ln1193_fu_769_p1");
    sc_trace(mVcdFile, mul_ln700_1_fu_764_p2, "mul_ln700_1_fu_764_p2");
    sc_trace(mVcdFile, mul_ln1193_fu_769_p2, "mul_ln1193_fu_769_p2");
    sc_trace(mVcdFile, ret_V_5_fu_774_p2, "ret_V_5_fu_774_p2");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, ap_condition_195, "ap_condition_195");
    sc_trace(mVcdFile, ap_condition_199, "ap_condition_199");
    sc_trace(mVcdFile, ap_condition_202, "ap_condition_202");
    sc_trace(mVcdFile, ap_condition_159, "ap_condition_159");
    sc_trace(mVcdFile, ap_condition_167, "ap_condition_167");
    sc_trace(mVcdFile, ap_condition_172, "ap_condition_172");
#endif

    }
}

shift::~shift() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete cos_table_U;
    delete sin_table_U;
}

void shift::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        m_0_reg_211 = m_reg_803.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        m_0_reg_211 = ap_const_lv17_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        p_Val2_s_reg_200 = value_V_4_reg_808.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        p_Val2_s_reg_200 = ap_const_lv32_FFEDC5D6;
    }
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, grp_fu_334_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, grp_fu_360_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln96_reg_863.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, and_ln65_fu_633_p2.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, grp_fu_334_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, grp_fu_360_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln96_reg_863.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, and_ln65_fu_633_p2.read())))) {
        sign_3_i3_reg_277 = ap_const_lv1_1;
    } else if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
                 esl_seteq<1,1,1>(grp_fu_334_p2.read(), ap_const_lv1_1) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln96_reg_863.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, and_ln65_fu_633_p2.read())) || 
                (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
                 esl_seteq<1,1,1>(icmp_ln96_reg_863.read(), ap_const_lv1_1)) || 
                (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln96_reg_863.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_1, and_ln65_fu_633_p2.read())))) {
        sign_3_i3_reg_277 = ap_const_lv1_0;
    }
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
          !(esl_seteq<1,1,1>(ap_const_logic_0, ary_r_V_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, ary_i_V_empty_n.read())) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln96_fu_496_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, and_ln100_fu_514_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, grp_fu_334_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, grp_fu_360_p2.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
          !(esl_seteq<1,1,1>(ap_const_logic_0, ary_r_V_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, ary_i_V_empty_n.read())) && 
          esl_seteq<1,1,1>(icmp_ln96_fu_496_p2.read(), ap_const_lv1_1)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
          !(esl_seteq<1,1,1>(ap_const_logic_0, ary_r_V_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, ary_i_V_empty_n.read())) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln96_fu_496_p2.read()) && 
          esl_seteq<1,1,1>(and_ln100_fu_514_p2.read(), ap_const_lv1_1)))) {
        sign_3_i_reg_239 = ap_const_lv1_0;
    } else if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
                 !(esl_seteq<1,1,1>(ap_const_logic_0, ary_r_V_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, ary_i_V_empty_n.read())) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln96_fu_496_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, and_ln100_fu_514_p2.read()) && 
                 esl_seteq<1,1,1>(grp_fu_334_p2.read(), ap_const_lv1_1)) || 
                (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
                 !(esl_seteq<1,1,1>(ap_const_logic_0, ary_r_V_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, ary_i_V_empty_n.read())) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln96_fu_496_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, and_ln100_fu_514_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, grp_fu_334_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_1, grp_fu_360_p2.read())))) {
        sign_3_i_reg_239 = ap_const_lv1_1;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        icmp_ln193_reg_924 = icmp_ln193_fu_790_p2.read();
        imag_V_reg_918 = ret_V_5_fu_774_p2.read().range(39, 8);
        real_V_reg_912 = ret_V_4_fu_748_p2.read().range(39, 8);
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln193_fu_790_p2.read()))) {
        icmp_ln198_reg_928 = icmp_ln198_fu_795_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && !(esl_seteq<1,1,1>(ap_const_logic_0, ary_r_V_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, ary_i_V_empty_n.read())))) {
        icmp_ln96_reg_863 = icmp_ln96_fu_496_p2.read();
        value_i_V_reg_858 = ary_i_V_dout.read();
        value_r_V_reg_853 = ary_r_V_dout.read();
        zext_ln189_reg_843 = zext_ln189_fu_492_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(icmp_ln161_fu_378_p2.read(), ap_const_lv1_0))) {
        idx_1_reg_833 = idx_1_fu_488_p1.read();
        select_ln850_reg_813 = select_ln850_fu_480_p3.read();
        value_V_4_reg_808 = value_V_4_fu_430_p3.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        m_reg_803 = m_fu_384_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        p_Val2_6_reg_907 = p_Val2_6_fu_724_p3.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        sext_ln1118_1_reg_887 = sext_ln1118_1_fu_616_p1.read();
        sext_ln1118_reg_881 = sext_ln1118_fu_613_p1.read();
    }
}

void shift::thread_add_ln1192_fu_402_p2() {
    add_ln1192_fu_402_p2 = (!ap_const_lv41_123A2900.is_01() || !zext_ln728_fu_398_p1.read().is_01())? sc_lv<41>(): (sc_biguint<41>(ap_const_lv41_123A2900) + sc_biguint<41>(zext_ln728_fu_398_p1.read()));
}

void shift::thread_and_ln100_fu_514_p2() {
    and_ln100_fu_514_p2 = (grp_fu_299_p2.read() & xor_ln100_fu_508_p2.read());
}

void shift::thread_and_ln65_fu_633_p2() {
    and_ln65_fu_633_p2 = (grp_fu_299_p2.read() & xor_ln65_fu_627_p2.read());
}

void shift::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void shift::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void shift::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void shift::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[3];
}

void shift::thread_ap_CS_fsm_state5() {
    ap_CS_fsm_state5 = ap_CS_fsm.read()[4];
}

void shift::thread_ap_CS_fsm_state6() {
    ap_CS_fsm_state6 = ap_CS_fsm.read()[5];
}

void shift::thread_ap_CS_fsm_state7() {
    ap_CS_fsm_state7 = ap_CS_fsm.read()[6];
}

void shift::thread_ap_block_state3() {
    ap_block_state3 = (esl_seteq<1,1,1>(ap_const_logic_0, ary_r_V_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, ary_i_V_empty_n.read()));
}

void shift::thread_ap_condition_159() {
    ap_condition_159 = (esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln96_fu_496_p2.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, and_ln100_fu_514_p2.read()) && esl_seteq<1,1,1>(grp_fu_334_p2.read(), ap_const_lv1_1));
}

void shift::thread_ap_condition_167() {
    ap_condition_167 = (esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln96_fu_496_p2.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, and_ln100_fu_514_p2.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, grp_fu_334_p2.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, grp_fu_360_p2.read()));
}

void shift::thread_ap_condition_172() {
    ap_condition_172 = (esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln96_fu_496_p2.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, and_ln100_fu_514_p2.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, grp_fu_334_p2.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, grp_fu_360_p2.read()));
}

void shift::thread_ap_condition_195() {
    ap_condition_195 = (esl_seteq<1,1,1>(grp_fu_334_p2.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln96_reg_863.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, and_ln65_fu_633_p2.read()));
}

void shift::thread_ap_condition_199() {
    ap_condition_199 = (esl_seteq<1,1,1>(ap_const_lv1_0, grp_fu_334_p2.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, grp_fu_360_p2.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln96_reg_863.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, and_ln65_fu_633_p2.read()));
}

void shift::thread_ap_condition_202() {
    ap_condition_202 = (esl_seteq<1,1,1>(ap_const_lv1_0, grp_fu_334_p2.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, grp_fu_360_p2.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln96_reg_863.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, and_ln65_fu_633_p2.read()));
}

void shift::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
          esl_seteq<1,1,1>(icmp_ln161_fu_378_p2.read(), ap_const_lv1_1)))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void shift::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void shift::thread_ap_phi_mux_idx_3_i2_phi_fu_264_p10() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        if ((esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln96_reg_863.read()) && 
             esl_seteq<1,1,1>(ap_const_lv1_1, and_ln65_fu_633_p2.read()))) {
            ap_phi_mux_idx_3_i2_phi_fu_264_p10 = select_ln850_reg_813.read();
        } else if (esl_seteq<1,1,1>(icmp_ln96_reg_863.read(), ap_const_lv1_1)) {
            ap_phi_mux_idx_3_i2_phi_fu_264_p10 = ap_const_lv16_0;
        } else if (esl_seteq<1,1,1>(ap_condition_202.read(), ap_const_boolean_1)) {
            ap_phi_mux_idx_3_i2_phi_fu_264_p10 = zext_ln78_fu_690_p1.read();
        } else if (esl_seteq<1,1,1>(ap_condition_199.read(), ap_const_boolean_1)) {
            ap_phi_mux_idx_3_i2_phi_fu_264_p10 = zext_ln74_fu_695_p1.read();
        } else if (esl_seteq<1,1,1>(ap_condition_195.read(), ap_const_boolean_1)) {
            ap_phi_mux_idx_3_i2_phi_fu_264_p10 = zext_ln70_1_fu_708_p1.read();
        } else {
            ap_phi_mux_idx_3_i2_phi_fu_264_p10 = "XXXXXXXXXXXXXXXX";
        }
    } else {
        ap_phi_mux_idx_3_i2_phi_fu_264_p10 = "XXXXXXXXXXXXXXXX";
    }
}

void shift::thread_ap_phi_mux_idx_3_i_phi_fu_226_p10() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        if ((esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln96_fu_496_p2.read()) && 
             esl_seteq<1,1,1>(and_ln100_fu_514_p2.read(), ap_const_lv1_1))) {
            ap_phi_mux_idx_3_i_phi_fu_226_p10 = select_ln850_reg_813.read();
        } else if (esl_seteq<1,1,1>(icmp_ln96_fu_496_p2.read(), ap_const_lv1_1)) {
            ap_phi_mux_idx_3_i_phi_fu_226_p10 = ap_const_lv16_0;
        } else if (esl_seteq<1,1,1>(ap_condition_172.read(), ap_const_boolean_1)) {
            ap_phi_mux_idx_3_i_phi_fu_226_p10 = zext_ln113_fu_571_p1.read();
        } else if (esl_seteq<1,1,1>(ap_condition_167.read(), ap_const_boolean_1)) {
            ap_phi_mux_idx_3_i_phi_fu_226_p10 = zext_ln109_fu_576_p1.read();
        } else if (esl_seteq<1,1,1>(ap_condition_159.read(), ap_const_boolean_1)) {
            ap_phi_mux_idx_3_i_phi_fu_226_p10 = zext_ln105_1_fu_589_p1.read();
        } else {
            ap_phi_mux_idx_3_i_phi_fu_226_p10 = "XXXXXXXXXXXXXXXX";
        }
    } else {
        ap_phi_mux_idx_3_i_phi_fu_226_p10 = "XXXXXXXXXXXXXXXX";
    }
}

void shift::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(icmp_ln161_fu_378_p2.read(), ap_const_lv1_1))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void shift::thread_ary_i_V_blk_n() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        ary_i_V_blk_n = ary_i_V_empty_n.read();
    } else {
        ary_i_V_blk_n = ap_const_logic_1;
    }
}

void shift::thread_ary_i_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ary_r_V_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, ary_i_V_empty_n.read())))) {
        ary_i_V_read = ap_const_logic_1;
    } else {
        ary_i_V_read = ap_const_logic_0;
    }
}

void shift::thread_ary_i_s_V_addr_1_gep_fu_176_p3() {
    ary_i_s_V_addr_1_gep_fu_176_p3 =  (sc_lv<17>) (zext_ln189_reg_843.read());
}

void shift::thread_ary_i_s_V_addr_gep_fu_192_p3() {
    ary_i_s_V_addr_gep_fu_192_p3 =  (sc_lv<17>) (zext_ln189_reg_843.read());
}

void shift::thread_ary_i_s_V_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        if (esl_seteq<1,1,1>(icmp_ln193_reg_924.read(), ap_const_lv1_1)) {
            ary_i_s_V_address0 = ary_i_s_V_addr_gep_fu_192_p3.read();
        } else if ((esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln193_reg_924.read()) && 
                    esl_seteq<1,1,1>(icmp_ln198_reg_928.read(), ap_const_lv1_1))) {
            ary_i_s_V_address0 = ary_i_s_V_addr_1_gep_fu_176_p3.read();
        } else if ((esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln193_reg_924.read()) && 
                    esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln198_reg_928.read()))) {
            ary_i_s_V_address0 =  (sc_lv<17>) (zext_ln189_reg_843.read());
        } else {
            ary_i_s_V_address0 =  (sc_lv<17>) ("XXXXXXXXXXXXXXXXX");
        }
    } else {
        ary_i_s_V_address0 =  (sc_lv<17>) ("XXXXXXXXXXXXXXXXX");
    }
}

void shift::thread_ary_i_s_V_ce0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln193_reg_924.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln198_reg_928.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln193_reg_924.read()) && 
          esl_seteq<1,1,1>(icmp_ln198_reg_928.read(), ap_const_lv1_1)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
          esl_seteq<1,1,1>(icmp_ln193_reg_924.read(), ap_const_lv1_1)))) {
        ary_i_s_V_ce0 = ap_const_logic_1;
    } else {
        ary_i_s_V_ce0 = ap_const_logic_0;
    }
}

void shift::thread_ary_i_s_V_d0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln193_reg_924.read()) && 
          esl_seteq<1,1,1>(icmp_ln198_reg_928.read(), ap_const_lv1_1)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
          esl_seteq<1,1,1>(icmp_ln193_reg_924.read(), ap_const_lv1_1)))) {
        ary_i_s_V_d0 = grp_fu_372_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln193_reg_924.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln198_reg_928.read()))) {
        ary_i_s_V_d0 = imag_V_reg_918.read();
    } else {
        ary_i_s_V_d0 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void shift::thread_ary_i_s_V_we0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln193_reg_924.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln198_reg_928.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln193_reg_924.read()) && 
          esl_seteq<1,1,1>(icmp_ln198_reg_928.read(), ap_const_lv1_1)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
          esl_seteq<1,1,1>(icmp_ln193_reg_924.read(), ap_const_lv1_1)))) {
        ary_i_s_V_we0 = ap_const_logic_1;
    } else {
        ary_i_s_V_we0 = ap_const_logic_0;
    }
}

void shift::thread_ary_r_V_blk_n() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        ary_r_V_blk_n = ary_r_V_empty_n.read();
    } else {
        ary_r_V_blk_n = ap_const_logic_1;
    }
}

void shift::thread_ary_r_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ary_r_V_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, ary_i_V_empty_n.read())))) {
        ary_r_V_read = ap_const_logic_1;
    } else {
        ary_r_V_read = ap_const_logic_0;
    }
}

void shift::thread_ary_r_s_V_addr_1_gep_fu_168_p3() {
    ary_r_s_V_addr_1_gep_fu_168_p3 =  (sc_lv<17>) (zext_ln189_reg_843.read());
}

void shift::thread_ary_r_s_V_addr_gep_fu_184_p3() {
    ary_r_s_V_addr_gep_fu_184_p3 =  (sc_lv<17>) (zext_ln189_reg_843.read());
}

void shift::thread_ary_r_s_V_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        if (esl_seteq<1,1,1>(icmp_ln193_reg_924.read(), ap_const_lv1_1)) {
            ary_r_s_V_address0 = ary_r_s_V_addr_gep_fu_184_p3.read();
        } else if ((esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln193_reg_924.read()) && 
                    esl_seteq<1,1,1>(icmp_ln198_reg_928.read(), ap_const_lv1_1))) {
            ary_r_s_V_address0 = ary_r_s_V_addr_1_gep_fu_168_p3.read();
        } else if ((esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln193_reg_924.read()) && 
                    esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln198_reg_928.read()))) {
            ary_r_s_V_address0 =  (sc_lv<17>) (zext_ln189_reg_843.read());
        } else {
            ary_r_s_V_address0 =  (sc_lv<17>) ("XXXXXXXXXXXXXXXXX");
        }
    } else {
        ary_r_s_V_address0 =  (sc_lv<17>) ("XXXXXXXXXXXXXXXXX");
    }
}

void shift::thread_ary_r_s_V_ce0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln193_reg_924.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln198_reg_928.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln193_reg_924.read()) && 
          esl_seteq<1,1,1>(icmp_ln198_reg_928.read(), ap_const_lv1_1)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
          esl_seteq<1,1,1>(icmp_ln193_reg_924.read(), ap_const_lv1_1)))) {
        ary_r_s_V_ce0 = ap_const_logic_1;
    } else {
        ary_r_s_V_ce0 = ap_const_logic_0;
    }
}

void shift::thread_ary_r_s_V_d0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln193_reg_924.read()) && 
          esl_seteq<1,1,1>(icmp_ln198_reg_928.read(), ap_const_lv1_1)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
          esl_seteq<1,1,1>(icmp_ln193_reg_924.read(), ap_const_lv1_1)))) {
        ary_r_s_V_d0 = grp_fu_366_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln193_reg_924.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln198_reg_928.read()))) {
        ary_r_s_V_d0 = real_V_reg_912.read();
    } else {
        ary_r_s_V_d0 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void shift::thread_ary_r_s_V_we0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln193_reg_924.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln198_reg_928.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln193_reg_924.read()) && 
          esl_seteq<1,1,1>(icmp_ln198_reg_928.read(), ap_const_lv1_1)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
          esl_seteq<1,1,1>(icmp_ln193_reg_924.read(), ap_const_lv1_1)))) {
        ary_r_s_V_we0 = ap_const_logic_1;
    } else {
        ary_r_s_V_we0 = ap_const_logic_0;
    }
}

void shift::thread_cos_table_address0() {
    cos_table_address0 =  (sc_lv<7>) (sext_ln1265_fu_594_p1.read());
}

void shift::thread_cos_table_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ary_r_V_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, ary_i_V_empty_n.read())))) {
        cos_table_ce0 = ap_const_logic_1;
    } else {
        cos_table_ce0 = ap_const_logic_0;
    }
}

void shift::thread_grp_fu_299_p2() {
    grp_fu_299_p2 = (!select_ln850_reg_813.read().is_01() || !ap_const_lv16_41.is_01())? sc_lv<1>(): (sc_bigint<16>(select_ln850_reg_813.read()) < sc_bigint<16>(ap_const_lv16_41));
}

void shift::thread_grp_fu_304_p4() {
    grp_fu_304_p4 = select_ln850_reg_813.read().range(15, 6);
}

void shift::thread_grp_fu_313_p2() {
    grp_fu_313_p2 = (!grp_fu_304_p4.read().is_01() || !ap_const_lv10_0.is_01())? sc_lv<1>(): (sc_bigint<10>(grp_fu_304_p4.read()) > sc_bigint<10>(ap_const_lv10_0));
}

void shift::thread_grp_fu_319_p4() {
    grp_fu_319_p4 = select_ln850_reg_813.read().range(15, 7);
}

void shift::thread_grp_fu_328_p2() {
    grp_fu_328_p2 = (!grp_fu_319_p4.read().is_01() || !ap_const_lv9_1.is_01())? sc_lv<1>(): (sc_bigint<9>(grp_fu_319_p4.read()) < sc_bigint<9>(ap_const_lv9_1));
}

void shift::thread_grp_fu_334_p2() {
    grp_fu_334_p2 = (grp_fu_313_p2.read() & grp_fu_328_p2.read());
}

void shift::thread_grp_fu_340_p4() {
    grp_fu_340_p4 = select_ln850_reg_813.read().range(15, 7);
}

void shift::thread_grp_fu_349_p2() {
    grp_fu_349_p2 = (!grp_fu_340_p4.read().is_01() || !ap_const_lv9_0.is_01())? sc_lv<1>(): (sc_bigint<9>(grp_fu_340_p4.read()) > sc_bigint<9>(ap_const_lv9_0));
}

void shift::thread_grp_fu_355_p2() {
    grp_fu_355_p2 = (!select_ln850_reg_813.read().is_01() || !ap_const_lv16_C0.is_01())? sc_lv<1>(): (sc_bigint<16>(select_ln850_reg_813.read()) < sc_bigint<16>(ap_const_lv16_C0));
}

void shift::thread_grp_fu_360_p2() {
    grp_fu_360_p2 = (grp_fu_349_p2.read() & grp_fu_355_p2.read());
}

void shift::thread_grp_fu_366_p2() {
    grp_fu_366_p2 = (!ap_const_lv32_0.is_01() || !real_V_reg_912.read().is_01())? sc_lv<32>(): (sc_biguint<32>(ap_const_lv32_0) - sc_biguint<32>(real_V_reg_912.read()));
}

void shift::thread_grp_fu_372_p2() {
    grp_fu_372_p2 = (!ap_const_lv32_0.is_01() || !imag_V_reg_918.read().is_01())? sc_lv<32>(): (sc_biguint<32>(ap_const_lv32_0) - sc_biguint<32>(imag_V_reg_918.read()));
}

void shift::thread_icmp_ln1494_fu_418_p2() {
    icmp_ln1494_fu_418_p2 = (!value_V_3_fu_408_p4.read().is_01() || !ap_const_lv32_1000000.is_01())? sc_lv<1>(): (sc_bigint<32>(value_V_3_fu_408_p4.read()) > sc_bigint<32>(ap_const_lv32_1000000));
}

void shift::thread_icmp_ln161_fu_378_p2() {
    icmp_ln161_fu_378_p2 = (!m_0_reg_211.read().is_01() || !ap_const_lv17_186A0.is_01())? sc_lv<1>(): sc_lv<1>(m_0_reg_211.read() == ap_const_lv17_186A0);
}

void shift::thread_icmp_ln193_fu_790_p2() {
    icmp_ln193_fu_790_p2 = (!select_ln850_reg_813.read().is_01() || !ap_const_lv16_0.is_01())? sc_lv<1>(): sc_lv<1>(select_ln850_reg_813.read() == ap_const_lv16_0);
}

void shift::thread_icmp_ln198_fu_795_p2() {
    icmp_ln198_fu_795_p2 = (!select_ln850_reg_813.read().is_01() || !ap_const_lv16_40.is_01())? sc_lv<1>(): sc_lv<1>(select_ln850_reg_813.read() == ap_const_lv16_40);
}

void shift::thread_icmp_ln851_fu_460_p2() {
    icmp_ln851_fu_460_p2 = (!trunc_ln851_fu_456_p1.read().is_01() || !ap_const_lv16_0.is_01())? sc_lv<1>(): sc_lv<1>(trunc_ln851_fu_456_p1.read() == ap_const_lv16_0);
}

void shift::thread_icmp_ln96_fu_496_p2() {
    icmp_ln96_fu_496_p2 = (!select_ln850_reg_813.read().is_01() || !ap_const_lv16_100.is_01())? sc_lv<1>(): sc_lv<1>(select_ln850_reg_813.read() == ap_const_lv16_100);
}

void shift::thread_idx_1_fu_488_p1() {
    idx_1_fu_488_p1 = select_ln850_fu_480_p3.read().range(6-1, 0);
}

void shift::thread_idx_2_fu_565_p2() {
    idx_2_fu_565_p2 = (!ap_const_lv7_40.is_01() || !select_ln113_fu_557_p3.read().is_01())? sc_lv<7>(): (sc_bigint<7>(ap_const_lv7_40) - sc_biguint<7>(select_ln113_fu_557_p3.read()));
}

void shift::thread_idx_3_fu_702_p2() {
    idx_3_fu_702_p2 = (!ap_const_lv7_40.is_01() || !zext_ln70_fu_699_p1.read().is_01())? sc_lv<7>(): (sc_bigint<7>(ap_const_lv7_40) - sc_biguint<7>(zext_ln70_fu_699_p1.read()));
}

void shift::thread_idx_4_fu_684_p2() {
    idx_4_fu_684_p2 = (!ap_const_lv7_40.is_01() || !select_ln78_fu_676_p3.read().is_01())? sc_lv<7>(): (sc_bigint<7>(ap_const_lv7_40) - sc_biguint<7>(select_ln78_fu_676_p3.read()));
}

void shift::thread_idx_fu_583_p2() {
    idx_fu_583_p2 = (!ap_const_lv7_40.is_01() || !zext_ln105_fu_580_p1.read().is_01())? sc_lv<7>(): (sc_bigint<7>(ap_const_lv7_40) - sc_biguint<7>(zext_ln105_fu_580_p1.read()));
}

void shift::thread_lhs_V_fu_390_p3() {
    lhs_V_fu_390_p3 = esl_concat<32,8>(p_Val2_s_reg_200.read(), ap_const_lv8_0);
}

void shift::thread_m_fu_384_p2() {
    m_fu_384_p2 = (!m_0_reg_211.read().is_01() || !ap_const_lv17_1.is_01())? sc_lv<17>(): (sc_biguint<17>(m_0_reg_211.read()) + sc_biguint<17>(ap_const_lv17_1));
}

void shift::thread_mul_ln1192_fu_742_p0() {
    mul_ln1192_fu_742_p0 =  (sc_lv<32>) (sext_ln1118_2_fu_732_p1.read());
}

void shift::thread_mul_ln1192_fu_742_p1() {
    mul_ln1192_fu_742_p1 =  (sc_lv<9>) (sext_ln1118_3_fu_735_p1.read());
}

void shift::thread_mul_ln1192_fu_742_p2() {
    mul_ln1192_fu_742_p2 = (!mul_ln1192_fu_742_p0.read().is_01() || !mul_ln1192_fu_742_p1.read().is_01())? sc_lv<40>(): sc_bigint<32>(mul_ln1192_fu_742_p0.read()) * sc_bigint<9>(mul_ln1192_fu_742_p1.read());
}

void shift::thread_mul_ln1193_fu_769_p0() {
    mul_ln1193_fu_769_p0 =  (sc_lv<32>) (sext_ln1118_reg_881.read());
}

void shift::thread_mul_ln1193_fu_769_p1() {
    mul_ln1193_fu_769_p1 =  (sc_lv<9>) (sext_ln1118_3_fu_735_p1.read());
}

void shift::thread_mul_ln1193_fu_769_p2() {
    mul_ln1193_fu_769_p2 = (!mul_ln1193_fu_769_p0.read().is_01() || !mul_ln1193_fu_769_p1.read().is_01())? sc_lv<40>(): sc_bigint<32>(mul_ln1193_fu_769_p0.read()) * sc_bigint<9>(mul_ln1193_fu_769_p1.read());
}

void shift::thread_mul_ln700_1_fu_764_p0() {
    mul_ln700_1_fu_764_p0 =  (sc_lv<32>) (sext_ln1118_2_fu_732_p1.read());
}

void shift::thread_mul_ln700_1_fu_764_p1() {
    mul_ln700_1_fu_764_p1 =  (sc_lv<9>) (sext_ln1118_1_reg_887.read());
}

void shift::thread_mul_ln700_1_fu_764_p2() {
    mul_ln700_1_fu_764_p2 = (!mul_ln700_1_fu_764_p0.read().is_01() || !mul_ln700_1_fu_764_p1.read().is_01())? sc_lv<40>(): sc_bigint<32>(mul_ln700_1_fu_764_p0.read()) * sc_bigint<9>(mul_ln700_1_fu_764_p1.read());
}

void shift::thread_mul_ln700_fu_738_p0() {
    mul_ln700_fu_738_p0 =  (sc_lv<32>) (sext_ln1118_reg_881.read());
}

void shift::thread_mul_ln700_fu_738_p1() {
    mul_ln700_fu_738_p1 =  (sc_lv<9>) (sext_ln1118_1_reg_887.read());
}

void shift::thread_mul_ln700_fu_738_p2() {
    mul_ln700_fu_738_p2 = (!mul_ln700_fu_738_p0.read().is_01() || !mul_ln700_fu_738_p1.read().is_01())? sc_lv<40>(): sc_bigint<32>(mul_ln700_fu_738_p0.read()) * sc_bigint<9>(mul_ln700_fu_738_p1.read());
}

void shift::thread_p_Result_s_fu_448_p3() {
    p_Result_s_fu_448_p3 = value_V_4_fu_430_p3.read().range(31, 31);
}

void shift::thread_p_Val2_4_fu_605_p3() {
    p_Val2_4_fu_605_p3 = (!sign_3_i_reg_239.read()[0].is_01())? sc_lv<9>(): ((sign_3_i_reg_239.read()[0].to_bool())? sub_ln703_4_fu_599_p2.read(): cos_table_q0.read());
}

void shift::thread_p_Val2_6_fu_724_p3() {
    p_Val2_6_fu_724_p3 = (!sign_3_i3_reg_277.read()[0].is_01())? sc_lv<9>(): ((sign_3_i3_reg_277.read()[0].to_bool())? sub_ln703_5_fu_718_p2.read(): sin_table_q0.read());
}

void shift::thread_ret_V_1_fu_466_p2() {
    ret_V_1_fu_466_p2 = (!ap_const_lv16_1.is_01() || !ret_V_fu_438_p4.read().is_01())? sc_lv<16>(): (sc_biguint<16>(ap_const_lv16_1) + sc_biguint<16>(ret_V_fu_438_p4.read()));
}

void shift::thread_ret_V_4_fu_748_p2() {
    ret_V_4_fu_748_p2 = (!mul_ln700_fu_738_p2.read().is_01() || !mul_ln1192_fu_742_p2.read().is_01())? sc_lv<40>(): (sc_biguint<40>(mul_ln700_fu_738_p2.read()) + sc_biguint<40>(mul_ln1192_fu_742_p2.read()));
}

void shift::thread_ret_V_5_fu_774_p2() {
    ret_V_5_fu_774_p2 = (!mul_ln700_1_fu_764_p2.read().is_01() || !mul_ln1193_fu_769_p2.read().is_01())? sc_lv<40>(): (sc_biguint<40>(mul_ln700_1_fu_764_p2.read()) - sc_biguint<40>(mul_ln1193_fu_769_p2.read()));
}

void shift::thread_ret_V_fu_438_p4() {
    ret_V_fu_438_p4 = value_V_4_fu_430_p3.read().range(31, 16);
}

void shift::thread_select_ln113_fu_557_p3() {
    select_ln113_fu_557_p3 = (!tmp_5_fu_520_p3.read()[0].is_01())? sc_lv<7>(): ((tmp_5_fu_520_p3.read()[0].to_bool())? sub_ln113_1_fu_544_p2.read(): tmp_3_fu_550_p3.read());
}

void shift::thread_select_ln78_fu_676_p3() {
    select_ln78_fu_676_p3 = (!tmp_12_fu_639_p3.read()[0].is_01())? sc_lv<7>(): ((tmp_12_fu_639_p3.read()[0].to_bool())? sub_ln78_1_fu_663_p2.read(): tmp_7_fu_669_p3.read());
}

void shift::thread_select_ln850_fu_480_p3() {
    select_ln850_fu_480_p3 = (!p_Result_s_fu_448_p3.read()[0].is_01())? sc_lv<16>(): ((p_Result_s_fu_448_p3.read()[0].to_bool())? select_ln851_fu_472_p3.read(): ret_V_fu_438_p4.read());
}

void shift::thread_select_ln851_fu_472_p3() {
    select_ln851_fu_472_p3 = (!icmp_ln851_fu_460_p2.read()[0].is_01())? sc_lv<16>(): ((icmp_ln851_fu_460_p2.read()[0].to_bool())? ret_V_fu_438_p4.read(): ret_V_1_fu_466_p2.read());
}

void shift::thread_sext_ln1118_1_fu_616_p1() {
    sext_ln1118_1_fu_616_p1 = esl_sext<40,9>(p_Val2_4_fu_605_p3.read());
}

void shift::thread_sext_ln1118_2_fu_732_p1() {
    sext_ln1118_2_fu_732_p1 = esl_sext<40,32>(value_i_V_reg_858.read());
}

void shift::thread_sext_ln1118_3_fu_735_p1() {
    sext_ln1118_3_fu_735_p1 = esl_sext<40,9>(p_Val2_6_reg_907.read());
}

void shift::thread_sext_ln1118_fu_613_p1() {
    sext_ln1118_fu_613_p1 = esl_sext<40,32>(value_r_V_reg_853.read());
}

void shift::thread_sext_ln1265_1_fu_713_p1() {
    sext_ln1265_1_fu_713_p1 = esl_sext<64,16>(ap_phi_mux_idx_3_i2_phi_fu_264_p10.read());
}

void shift::thread_sext_ln1265_fu_594_p1() {
    sext_ln1265_fu_594_p1 = esl_sext<64,16>(ap_phi_mux_idx_3_i_phi_fu_226_p10.read());
}

void shift::thread_sin_table_address0() {
    sin_table_address0 =  (sc_lv<7>) (sext_ln1265_1_fu_713_p1.read());
}

void shift::thread_sin_table_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        sin_table_ce0 = ap_const_logic_1;
    } else {
        sin_table_ce0 = ap_const_logic_0;
    }
}

void shift::thread_sub_ln113_1_fu_544_p2() {
    sub_ln113_1_fu_544_p2 = (!ap_const_lv7_0.is_01() || !tmp_6_fu_536_p3.read().is_01())? sc_lv<7>(): (sc_biguint<7>(ap_const_lv7_0) - sc_biguint<7>(tmp_6_fu_536_p3.read()));
}

void shift::thread_sub_ln113_fu_530_p2() {
    sub_ln113_fu_530_p2 = (!ap_const_lv6_0.is_01() || !trunc_ln113_fu_527_p1.read().is_01())? sc_lv<6>(): (sc_biguint<6>(ap_const_lv6_0) - sc_biguint<6>(trunc_ln113_fu_527_p1.read()));
}

void shift::thread_sub_ln703_4_fu_599_p2() {
    sub_ln703_4_fu_599_p2 = (!ap_const_lv9_0.is_01() || !cos_table_q0.read().is_01())? sc_lv<9>(): (sc_biguint<9>(ap_const_lv9_0) - sc_biguint<9>(cos_table_q0.read()));
}

void shift::thread_sub_ln703_5_fu_718_p2() {
    sub_ln703_5_fu_718_p2 = (!ap_const_lv9_0.is_01() || !sin_table_q0.read().is_01())? sc_lv<9>(): (sc_biguint<9>(ap_const_lv9_0) - sc_biguint<9>(sin_table_q0.read()));
}

void shift::thread_sub_ln78_1_fu_663_p2() {
    sub_ln78_1_fu_663_p2 = (!ap_const_lv7_0.is_01() || !tmp_13_fu_655_p3.read().is_01())? sc_lv<7>(): (sc_biguint<7>(ap_const_lv7_0) - sc_biguint<7>(tmp_13_fu_655_p3.read()));
}

void shift::thread_sub_ln78_fu_649_p2() {
    sub_ln78_fu_649_p2 = (!ap_const_lv6_0.is_01() || !trunc_ln78_fu_646_p1.read().is_01())? sc_lv<6>(): (sc_biguint<6>(ap_const_lv6_0) - sc_biguint<6>(trunc_ln78_fu_646_p1.read()));
}

void shift::thread_tmp_12_fu_639_p3() {
    tmp_12_fu_639_p3 = select_ln850_reg_813.read().range(15, 15);
}

void shift::thread_tmp_13_fu_655_p3() {
    tmp_13_fu_655_p3 = esl_concat<1,6>(ap_const_lv1_0, sub_ln78_fu_649_p2.read());
}

void shift::thread_tmp_3_fu_550_p3() {
    tmp_3_fu_550_p3 = esl_concat<1,6>(ap_const_lv1_0, idx_1_reg_833.read());
}

void shift::thread_tmp_5_fu_520_p3() {
    tmp_5_fu_520_p3 = select_ln850_reg_813.read().range(15, 15);
}

void shift::thread_tmp_6_fu_536_p3() {
    tmp_6_fu_536_p3 = esl_concat<1,6>(ap_const_lv1_0, sub_ln113_fu_530_p2.read());
}

void shift::thread_tmp_7_fu_669_p3() {
    tmp_7_fu_669_p3 = esl_concat<1,6>(ap_const_lv1_0, idx_1_reg_833.read());
}

void shift::thread_tmp_8_fu_620_p3() {
    tmp_8_fu_620_p3 = select_ln850_reg_813.read().range(15, 15);
}

void shift::thread_tmp_fu_501_p3() {
    tmp_fu_501_p3 = select_ln850_reg_813.read().range(15, 15);
}

void shift::thread_trunc_ln113_fu_527_p1() {
    trunc_ln113_fu_527_p1 = select_ln850_reg_813.read().range(6-1, 0);
}

void shift::thread_trunc_ln78_fu_646_p1() {
    trunc_ln78_fu_646_p1 = select_ln850_reg_813.read().range(6-1, 0);
}

void shift::thread_trunc_ln851_fu_456_p1() {
    trunc_ln851_fu_456_p1 = value_V_4_fu_430_p3.read().range(16-1, 0);
}

void shift::thread_value_V_3_fu_408_p4() {
    value_V_3_fu_408_p4 = add_ln1192_fu_402_p2.read().range(39, 8);
}

void shift::thread_value_V_4_fu_430_p3() {
    value_V_4_fu_430_p3 = (!icmp_ln1494_fu_418_p2.read()[0].is_01())? sc_lv<32>(): ((icmp_ln1494_fu_418_p2.read()[0].to_bool())? value_V_fu_424_p2.read(): value_V_3_fu_408_p4.read());
}

void shift::thread_value_V_fu_424_p2() {
    value_V_fu_424_p2 = (!ap_const_lv32_FF000000.is_01() || !value_V_3_fu_408_p4.read().is_01())? sc_lv<32>(): (sc_bigint<32>(ap_const_lv32_FF000000) + sc_biguint<32>(value_V_3_fu_408_p4.read()));
}

void shift::thread_xor_ln100_fu_508_p2() {
    xor_ln100_fu_508_p2 = (tmp_fu_501_p3.read() ^ ap_const_lv1_1);
}

void shift::thread_xor_ln65_fu_627_p2() {
    xor_ln65_fu_627_p2 = (tmp_8_fu_620_p3.read() ^ ap_const_lv1_1);
}

void shift::thread_zext_ln105_1_fu_589_p1() {
    zext_ln105_1_fu_589_p1 = esl_zext<16,7>(idx_fu_583_p2.read());
}

void shift::thread_zext_ln105_fu_580_p1() {
    zext_ln105_fu_580_p1 = esl_zext<7,6>(idx_1_reg_833.read());
}

void shift::thread_zext_ln109_fu_576_p1() {
    zext_ln109_fu_576_p1 = esl_zext<16,6>(idx_1_reg_833.read());
}

void shift::thread_zext_ln113_fu_571_p1() {
    zext_ln113_fu_571_p1 = esl_zext<16,7>(idx_2_fu_565_p2.read());
}

void shift::thread_zext_ln189_fu_492_p1() {
    zext_ln189_fu_492_p1 = esl_zext<64,17>(m_0_reg_211.read());
}

void shift::thread_zext_ln70_1_fu_708_p1() {
    zext_ln70_1_fu_708_p1 = esl_zext<16,7>(idx_3_fu_702_p2.read());
}

void shift::thread_zext_ln70_fu_699_p1() {
    zext_ln70_fu_699_p1 = esl_zext<7,6>(idx_1_reg_833.read());
}

void shift::thread_zext_ln728_fu_398_p1() {
    zext_ln728_fu_398_p1 = esl_zext<41,40>(lhs_V_fu_390_p3.read());
}

void shift::thread_zext_ln74_fu_695_p1() {
    zext_ln74_fu_695_p1 = esl_zext<16,6>(idx_1_reg_833.read());
}

void shift::thread_zext_ln78_fu_690_p1() {
    zext_ln78_fu_690_p1 = esl_zext<16,7>(idx_4_fu_684_p2.read());
}

void shift::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(icmp_ln161_fu_378_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state3;
            }
            break;
        case 4 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && !(esl_seteq<1,1,1>(ap_const_logic_0, ary_r_V_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, ary_i_V_empty_n.read())))) {
                ap_NS_fsm = ap_ST_fsm_state4;
            } else {
                ap_NS_fsm = ap_ST_fsm_state3;
            }
            break;
        case 8 : 
            ap_NS_fsm = ap_ST_fsm_state5;
            break;
        case 16 : 
            ap_NS_fsm = ap_ST_fsm_state6;
            break;
        case 32 : 
            ap_NS_fsm = ap_ST_fsm_state7;
            break;
        case 64 : 
            ap_NS_fsm = ap_ST_fsm_state2;
            break;
        default : 
            ap_NS_fsm =  (sc_lv<7>) ("XXXXXXX");
            break;
    }
}

}

